/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACCuentasBancarias : Base
    {
        #region Fill
        public static Entity_CuentasBancarias Fill(Entity_CuentasBancarias obj)
        {
            IDataReader drd;
            Entity_CuentasBancarias oEntity_CuentasBancarias;
            oEntity_CuentasBancarias = new Entity_CuentasBancarias();

            try
            {
                SqlParameter[] arrPar = new SqlParameter[2];
                arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
                arrPar[0].Value = obj.IntEmpresa;
                arrPar[1] = new SqlParameter("@intCuentaBancaria", SqlDbType.Int);
                arrPar[1].Value = obj.intCuentaBancaria;

                drd = SqlHelper.ExecuteReader(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbCuentasBancarias_Sele", arrPar);
                if (drd.Read())
                {
                    oEntity_CuentasBancarias = CreateObject(drd);
                }
                else
                {
                    oEntity_CuentasBancarias = null;
                }
            }
            catch (Exception e)
            {
                oEntity_CuentasBancarias = null;
            }

            return oEntity_CuentasBancarias;
        }
        #endregion

        #region Create
        static Entity_CuentasBancarias CreateObject(IDataReader drd)
        {
            Entity_CuentasBancarias obj;
            obj = new Entity_CuentasBancarias();

            obj.IntEmpresa = (int)drd["intEmpresa"];
            obj.intCuentaBancaria = (int)drd["intCuentaBancaria"];
            obj.intBanco = (int)drd["intBanco"];
            obj.strNombre = (string)drd["strNombre"];
            obj.strSucursal = (string)drd["strSucursal"];
            obj.strNumCuenta = (string)drd["strNumCuenta"];
            obj.strCCBanco = (string)drd["strCCBanco"];
            obj.strCCComplem = (string)drd["strCCComplem"];
            obj.strCCTransferencia = (string)drd["strCCTransferencia"];
            obj.strTipoPoliza = (string)drd["strTipoPoliza"];
            obj.intTipoMoneda = (int)drd["intTipoMoneda"];
            obj.intIdioma = (int)drd["intIdioma"];
            obj.intFolio = (int)drd["intFolio"];
            obj.intFolioTransferencia = (int)drd["intFolioTransferencia"];
            obj.dblSaldo = (double)drd["dblSaldo"];
            obj.strUsuarioAlta = (string)drd["strUsuarioAlta"];
            obj.strMaquinaAlta = (string)drd["strMaquinaAlta"];
            obj.datFechaAlta = (DateTime)drd["datFechaAlta"];
            obj.strUsuarioMod = (string)drd["strUsuarioMod"];
            obj.strMaquinaMod = (string)drd["strMaquinaMod"];
            obj.datFechaMod = (DateTime)drd["datFechaMod"];
            obj.strCCBancoOrig = (string)drd["strCCBancoOrig"];
            obj.strCCComplemOrig = (string)drd["strCCComplemOrig"];
            obj.strReporte = (string)drd["strReporte"];
            obj.intPoliza = (int)drd["intPoliza"];
            obj.intProveedor = (int)drd["intProveedor"];

            try
            {
                obj.iNumPage = (int)drd["iTotalPages"];
                obj.iNumRecords = (int)drd["iTotalRecords"];

            }
            catch (Exception e)
            {

            }

            return obj;
        }
        #endregion

        #region Save
        public static string Save(Entity_CuentasBancarias obj)
        {
            string result = "";
            SqlParameter[] arrPar = new SqlParameter[26];

            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;

            arrPar[1] = new SqlParameter("@intCuentaBancaria", SqlDbType.Int);
            arrPar[1].Value = obj.intCuentaBancaria;

            arrPar[2] = new SqlParameter("@intBanco", SqlDbType.Int);
            arrPar[2].Value = obj.intBanco;

            arrPar[3] = new SqlParameter("@strNombre", SqlDbType.VarChar);
            arrPar[3].Value = obj.strNombre;

            arrPar[4] = new SqlParameter("@strSucursal", SqlDbType.VarChar);
            arrPar[4].Value = obj.strSucursal;

            arrPar[5] = new SqlParameter("@strNumCuenta", SqlDbType.VarChar);
            arrPar[5].Value = obj.strNumCuenta;

            arrPar[6] = new SqlParameter("@strCCBanco", SqlDbType.VarChar);
            arrPar[6].Value = obj.strCCBanco;

            arrPar[7] = new SqlParameter("@strCCComplem", SqlDbType.VarChar);
            arrPar[7].Value = obj.strCCComplem;

            arrPar[8] = new SqlParameter("@strCCTransferencia", SqlDbType.VarChar);
            arrPar[8].Value = obj.strCCTransferencia;

            arrPar[9] = new SqlParameter("@strTipoPoliza", SqlDbType.VarChar);
            arrPar[9].Value = obj.strTipoPoliza;

            arrPar[10] = new SqlParameter("@intTipoMoneda", SqlDbType.Int);
            arrPar[10].Value = obj.intTipoMoneda;

            arrPar[11] = new SqlParameter("@intIdioma", SqlDbType.Int);
            arrPar[11].Value = obj.intIdioma;

            arrPar[12] = new SqlParameter("@intFolio", SqlDbType.Int);
            arrPar[12].Value = obj.intFolio;

            arrPar[13] = new SqlParameter("@intFolioTransferencia", SqlDbType.Int);
            arrPar[13].Value = obj.intFolioTransferencia;

            arrPar[14] = new SqlParameter("@dblSaldo", SqlDbType.Float);
            arrPar[14].Value = obj.dblSaldo;

            arrPar[15] = new SqlParameter("@strUsuarioAlta", SqlDbType.VarChar);
            arrPar[15].Value = obj.strUsuarioAlta;

            arrPar[16] = new SqlParameter("@strMaquinaAlta", SqlDbType.VarChar);
            arrPar[16].Value = obj.strMaquinaAlta;

            arrPar[17] = new SqlParameter("@datFechaAlta", SqlDbType.DateTime);
            arrPar[17].Value = obj.datFechaAlta;

            arrPar[18] = new SqlParameter("@strUsuarioMod", SqlDbType.VarChar);
            arrPar[18].Value = obj.strUsuarioMod;

            arrPar[19] = new SqlParameter("@strMaquinaMod ", SqlDbType.VarChar);
            arrPar[19].Value = obj.strMaquinaMod;

            arrPar[20] = new SqlParameter("@datFechaMod", SqlDbType.DateTime);
            arrPar[20].Value = obj.datFechaMod;

            arrPar[21] = new SqlParameter("@strCCBancoOrig", SqlDbType.VarChar);
            arrPar[21].Value = obj.strCCBancoOrig;

            arrPar[22] = new SqlParameter("@strCCComplemOrig", SqlDbType.VarChar);
            arrPar[22].Value = obj.strCCComplemOrig;

            arrPar[23] = new SqlParameter("@strReporte", SqlDbType.VarChar);
            arrPar[23].Value = obj.strReporte;

            arrPar[24] = new SqlParameter("@intPoliza", SqlDbType.Int);
            arrPar[24].Value = obj.intPoliza;

            arrPar[25] = new SqlParameter("@intProveedor", SqlDbType.Int);
            arrPar[25].Value = obj.intProveedor;

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbCuentasBancarias_Save", arrPar).ToString();
            }
            catch (Exception e)
            {
                throw e;
            }

            return result;
        }

        #endregion

        #region Delete
        public static bool Delete(Entity_CuentasBancarias obj)
        {

            bool bResult = false;

            SqlParameter[] arrPar = new SqlParameter[2];

            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;

            arrPar[1] = new SqlParameter("@intCuentaBancaria", SqlDbType.Int);
            arrPar[1].Value = obj.intCuentaBancaria;

            try
            {
                SqlHelper.ExecuteNonQuery(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbCuentasBancarias_Del", arrPar);
                bResult = false;
            }
            catch (Exception e)
            {
                throw e;
            }

            return bResult;
        }
        #endregion Delete
    }
}
