/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACClientes : Base
    {
        #region Fill
        public static Entity_Clientes  Fill(int IdUser)
        {
            IDataReader drd;
            Entity_Clientes oEntity_Clientes;
            oEntity_Clientes = new Entity_Clientes();

            SqlParameter[] arrPar = new SqlParameter[1];
            arrPar[0] = new SqlParameter("@p_IdUser", SqlDbType.Int);
            arrPar[0].Value = IdUser;

            try
            {
                drd = SqlHelper.ExecuteReader(ConnectionString, CommandType.StoredProcedure, "usp_catUser_sel", arrPar);
                if (drd.Read())
                {
                    oEntity_Clientes = CreateObject(drd);
                }
            }
            catch (Exception e)
            {
                oEntity_Clientes = null;
            }

            return oEntity_Clientes;
        }
        #endregion  

        #region Sel
        public static DataTable  Sel(Entity_Clientes obj)
        {
            DataSet ds;

            Entity_Clientes oEntity_Clientes;
            oEntity_Clientes = new Entity_Clientes();

            SqlParameter[] arrPar = new SqlParameter[2];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.intEmpresa  ;
            arrPar[1] = new SqlParameter("@auxiliar", SqlDbType.VarChar);
            arrPar[1].Value = obj.strClave ;

            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.Text, "SELECT strClave  as id, strNombre FROM tbClientes WHERE intEmpresa=" + obj.intEmpresa + " AND strClave = '" + obj.strClave + "'");
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion  

        #region Create
        static Entity_Clientes CreateObject(IDataReader drd)
        {
            Entity_Clientes obj;
            obj = new Entity_Clientes();

            obj.intEmpresa = (int)drd["intEmpresa"];
            obj.intSucursal = (int)drd["intSucursal"];
            obj.intCliente = (int)drd["intCliente"];
            obj.strNombre = (string )drd["strNombre"];
            obj.strDireccion = (string)drd["strDireccion"];
            obj.strColonia = (string)drd["strColonia"];

            return obj;
        }
        #endregion
    }
}
