/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACServidor : Base
	{

        public static Entity_Servidor Credenciales()
        {
            Contabilidad.Entity.Entity_Servidor obj = new Entity_Servidor();
            obj.StrSQLIP = "192.168.80.5";
            obj.StrSQLUser = "sa";
            obj.StrSQLPass = "M1rf3l";
            //obj.StrSQLIP = "192.168.100.10";
            //obj.StrSQLUser = "vetec";
            //obj.StrSQLPass = "vetec";
            return obj;
        }

	}
}
