/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACCerrarPeriodo : Base
    {
        #region GetList
        public static DataTable GetList(Entity_CerrarPeriodo obj)
        {
            DataSet ds;

            SqlParameter[] arrPar = new SqlParameter[3];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.intEmpresa;
            arrPar[1] = new SqlParameter("@intEjercicio", SqlDbType.Int);
            arrPar[1].Value = obj.intEjercicio;
            arrPar[2] = new SqlParameter("@intMes", SqlDbType.Int);
            arrPar[2].Value = obj.intMes;

            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, "usp_tbCerrarPeriodo_List", arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion

        #region Save
        public static bool Save(Entity_CerrarPeriodo obj)
        {

            bool bResult = false;

            SqlParameter[] arrPar = new SqlParameter[6];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.intEmpresa;
            arrPar[1] = new SqlParameter("@intEjercicio", SqlDbType.Int);
            arrPar[1].Value = obj.intEjercicio;
            arrPar[2] = new SqlParameter("@intMes", SqlDbType.Int);
            arrPar[2].Value = obj.intMes;
            arrPar[3] = new SqlParameter("@intModulo", SqlDbType.Int);
            arrPar[3].Value = obj.intModulo;
            arrPar[4] = new SqlParameter("@bCerrado", SqlDbType.Bit);
            arrPar[4].Value = obj.bCerrado;
            arrPar[5] = new SqlParameter("@strUsuario", SqlDbType.VarChar);
            arrPar[5].Value = obj.StrUsuario;              
            
            try
            {
                SqlHelper.ExecuteNonQuery(ConnectionString, CommandType.StoredProcedure, "usp_tbCerrarPeriodo_Save", arrPar);
                bResult = false;
            }
            catch (Exception e)
            {
                throw e;
            }

            return bResult;
        }
        #endregion Save

        #region Close
        public static string  Close(Entity_CerrarPeriodo obj)
        {
            string result = "";

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.Text, "SELECT VetecMarfil.dbo.fn_tbCerrarPeriodo(" + obj.intEmpresa.ToString() + "," + obj.intEjercicio.ToString() + "," + obj.intMes.ToString() + ","+obj.intModulo.ToString()+")").ToString();
            }
            catch (Exception e)
            {
                return null;
            }

            return result;
        }
        #endregion

			
    }
}
