/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-08-19
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACConciliaciones : Base
    {
        #region GetList
        public static DataTable GetList(int intEmpresa)
        {
            DataSet ds;

            SqlParameter[] arrPar = new SqlParameter[1];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = intEmpresa;
            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, "usp_tbTempConciliacionEjercicio_Sel", arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion

        #region List
        public static DataTable List(Entity_Conciliaciones obj)
        {
            DataSet ds;
            DataTable dt;

            SqlParameter[] arrPar = new SqlParameter[6];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;
            arrPar[1] = new SqlParameter("@intEjercicio", SqlDbType.Int);
            arrPar[1].Value = obj.IntEjercicio;
            arrPar[2] = new SqlParameter("@intMes", SqlDbType.Int);
            arrPar[2].Value = obj.IntMes;
            arrPar[3] = new SqlParameter("@intCuentaBancaria", SqlDbType.Int);
            arrPar[3].Value = obj.intCuentaBancaria;
            arrPar[4] = new SqlParameter("@intDireccion", SqlDbType.Int);
            arrPar[4].Value = obj.IntDireccion ;
            arrPar[5] = new SqlParameter("@SortExpression", SqlDbType.VarChar);
            arrPar[5].Value = obj.SortExpression ;

            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, "usp_tbTempConciliacion_List", arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion

        #region TemConciliacion
        public static bool  TemConciliacion(Entity_Conciliaciones obj)
        {
            bool bResult = false;

            SqlParameter[] arrPar = new SqlParameter[11];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;
            arrPar[1] = new SqlParameter("@intEjercicio", SqlDbType.Int);
            arrPar[1].Value = obj.IntEjercicio;
            arrPar[2] = new SqlParameter("@intMes", SqlDbType.Int);
            arrPar[2].Value = obj.IntMes;
            arrPar[3] = new SqlParameter("@intCuentaBancaria", SqlDbType.Int);
            arrPar[3].Value = obj.intCuentaBancaria;
            arrPar[4] = new SqlParameter("@strCuentaBancaria", SqlDbType.VarChar);
            arrPar[4].Value = obj.strKeys;
            arrPar[5] = new SqlParameter("@strReferencia", SqlDbType.VarChar);
            arrPar[5].Value = obj.StrReferencia ;
            arrPar[6] = new SqlParameter("@dblMonto", SqlDbType.Decimal);
            arrPar[6].Value = obj.DblImporte ;
            arrPar[7] = new SqlParameter("@strDescripcion", SqlDbType.VarChar);
            arrPar[7].Value = obj.StrConcepto ;
            arrPar[8] = new SqlParameter("@datFecha", SqlDbType.VarChar);
            arrPar[8].Value = obj.DatFecha ;
            arrPar[9] = new SqlParameter("@strUsuario", SqlDbType.VarChar);
            arrPar[9].Value = obj.StrUsuario ;
            arrPar[10] = new SqlParameter("@strMaquina", SqlDbType.VarChar);
            arrPar[10].Value = obj.StrMaquina;


            try
            {
                SqlHelper.ExecuteNonQuery(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..qryINCN2110_App_tbTemConciliacion", arrPar);
                bResult = false;
            }
            catch (Exception e)
            {
                throw e;
            }

            return bResult;

        }
        #endregion

        #region Del
        public static bool Del(Entity_Conciliaciones obj)
        {
            bool bResult = false;

            SqlParameter[] arrPar = new SqlParameter[4];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;
            arrPar[1] = new SqlParameter("@intEjercicio", SqlDbType.Int);
            arrPar[1].Value = obj.IntEjercicio;
            arrPar[2] = new SqlParameter("@intMes", SqlDbType.Int);
            arrPar[2].Value = obj.IntMes;
            arrPar[3] = new SqlParameter("@intCuentaBancaria", SqlDbType.Int);
            arrPar[3].Value = obj.intCuentaBancaria;

            try
            {
                SqlHelper.ExecuteNonQuery(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbTempConciliacion_Del", arrPar);
                bResult = false;
            }
            catch (Exception e)
            {
                throw e;
            }

            return bResult;
        }
        #endregion Del

        #region Val
        public static string Val(Entity_Conciliaciones obj)
        {
            string result;

            SqlParameter[] arrPar = new SqlParameter[4];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa ;
            arrPar[1] = new SqlParameter("@intEjercicio", SqlDbType.Int);
            arrPar[1].Value = obj.IntEjercicio ;
            arrPar[2] = new SqlParameter("@intMes", SqlDbType.Int);
            arrPar[2].Value = obj.IntMes ;
            arrPar[3] = new SqlParameter("@intCuentaBancaria", SqlDbType.Int);
            arrPar[3].Value = obj.intCuentaBancaria;

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "vetecmarfilAdmin..usp_tbTempConciliacion_Val", arrPar).ToString();
            }
            catch (Exception e)
            {
                throw e;
            }

            return result;
        }
        #endregion        

        #region QueryHelp
        public override string QueryHelp(int intEmpresa, int intSucursal, string[] parametros, int version)
        {
            string value = "";
            string parameter = "";

            for (int i = 0; i < parametros.Length; i++)
            {
                parameter = parameter + parametros[i].ToString() + ",";
            }

            SqlParameter[] arrPar = new SqlParameter[4];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = intEmpresa;
            arrPar[1] = new SqlParameter("@intSucursal", SqlDbType.Int);
            arrPar[1].Value = intSucursal;
            arrPar[2] = new SqlParameter("@intVersion", SqlDbType.Int);
            arrPar[2].Value = version;
            arrPar[3] = new SqlParameter("@strParametros", SqlDbType.VarChar);
            arrPar[3].Value = parameter;
            try
            {
                value = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbConciliaciones_Help", arrPar).ToString();
                return value;
            }
            catch (Exception e)
            {
                return "";
            }

            return value;
        }
        #endregion

    }
}
