/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto
'  Date: 2013-09-03
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACEstados : Base
    {
        #region Fill
        public static Entity_Estados  Fill(Entity_Estados obj)
        {
            IDataReader drd;
            Entity_Estados oEntity_Estados;
            oEntity_Estados = new Entity_Estados();

            SqlParameter[] arrPar = new SqlParameter[1];
            arrPar[0] = new SqlParameter("@intEstado", SqlDbType.Int);
            arrPar[0].Value = obj.intEstado;

            try
            {
                drd = SqlHelper.ExecuteReader(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbEstados_Sel", arrPar);
                if (drd.Read())
                {
                    oEntity_Estados = CreateObject(drd);
                }
            }
            catch (Exception e)
            {
                oEntity_Estados = null;
            }

            return oEntity_Estados;
        }
        #endregion  

        #region Create
        static Entity_Estados CreateObject(IDataReader drd)
        {
            Entity_Estados obj;
            obj = new Entity_Estados();

            obj.intEstado = (int)drd["intEstado"];
            obj.strNombre = (string )drd["strNombre"];
            obj.strNombreCorto = (string )drd["strNombreCorto"];
            obj.intPais = (int)drd["intPais"];
            obj.strAuditAlta = (string)drd["strAuditAlta"];
            obj.strAuditMod = (string)drd["strAuditMod"];

            return obj;
        }
        #endregion
    }
}
