/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-09-02
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACEstadosFinRubros : Base
    {
        #region Sel
        public static DataTable GetList(Entity_EstadosFinRubros obj)
        {
            DataSet ds;

            SqlParameter[] arrPar = new SqlParameter[2];
            arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
            arrPar[0].Value = obj.intEstadoFin;
            arrPar[1] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[1].Value = obj.intEmpresa;
            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFinRubros_Fill", arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion

        #region Fill
        public static Entity_EstadosFinRubros Fill(Entity_EstadosFinRubros obj)
        {
            IDataReader drd;
            Entity_EstadosFinRubros oEntity_Rubros;
            oEntity_Rubros = new Entity_EstadosFinRubros();

            try
            {
                SqlParameter[] arrPar = new SqlParameter[3];
                arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
                arrPar[0].Value = obj.intEstadoFin;
                arrPar[1] = new SqlParameter("@intRubro", SqlDbType.Int);
                arrPar[1].Value = obj.intRubro;
                arrPar[2] = new SqlParameter("@intEmpresa", SqlDbType.Int);
                arrPar[2].Value = obj.intEmpresa;

                drd = SqlHelper.ExecuteReader(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFinRubros_Del", arrPar);
                if (drd.Read())
                {
                    oEntity_Rubros = CreateObject(drd);
                }
                else
                {
                    oEntity_Rubros = null;
                }
            }
            catch (Exception e)
            {
                oEntity_Rubros = null;
            }

            return oEntity_Rubros;
        }
        #endregion

        #region Create
        static Entity_EstadosFinRubros CreateObject(IDataReader drd)
        {
            Entity_EstadosFinRubros obj = new Entity_EstadosFinRubros();

            obj.intEstadoFin = Convert.ToInt32(drd["intEstadoFin"].ToString());
            obj.intRubro = Convert.ToInt32(drd["intRubro"].ToString());
            obj.intSecuencia = Convert.ToInt32(drd["intSecuencia"].ToString());
            obj.strTipoRubro = drd["strTipoRubro"].ToString();
            obj.strNombre = drd["strNombre"].ToString();
            obj.strNombreCorto = drd["strNombreCorto"].ToString();
            obj.intPtaje = Convert.ToInt32(drd["intPtaje"].ToString());
            obj.datFechaAlta = Convert.ToDateTime(drd["datFechaAlta"].ToString());
            obj.strUsuarioAlta = drd["strUsuarioAlta"].ToString();
            obj.strMaquinaAlta = drd["strMaquinaAlta"].ToString();
            obj.datFechaMod = Convert.ToDateTime(drd["datFechaMod"].ToString());
            obj.strUsuarioMod = drd["strUsuarioMod"].ToString();
            obj.strMaquinaMod = drd["strMaquinaMod"].ToString();
            obj.intEmpresa = Convert.ToInt32(drd["intEmpresa"].ToString());

            return obj;
        }
        #endregion

        #region Save
        public static string Save(Entity_EstadosFinRubros obj)
        {
            string result = "";
            SqlParameter[] arrPar = new SqlParameter[14];

            arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
            arrPar[0].Value = obj.intEstadoFin;
            arrPar[1] = new SqlParameter("@intRubro", SqlDbType.Int );
            arrPar[1].Value = obj.intRubro;
            arrPar[2] = new SqlParameter("@intSecuencia", SqlDbType.Int);
            arrPar[2].Value = obj.intSecuencia;
            arrPar[3] = new SqlParameter("@strTipoRubro", SqlDbType.VarChar );
            arrPar[3].Value = obj.strTipoRubro;
            arrPar[4] = new SqlParameter("@strNombre", SqlDbType.VarChar );
            arrPar[4].Value = obj.strNombre;
            arrPar[5] = new SqlParameter("@strNombreCorto", SqlDbType.VarChar);
            arrPar[5].Value = obj.strNombreCorto;
            arrPar[6] = new SqlParameter("@intPtaje", SqlDbType.Int);
            arrPar[6].Value = obj.intPtaje;
            arrPar[7] = new SqlParameter("@datFechaAlta", SqlDbType.DateTime);
            arrPar[7].Value = obj.datFechaAlta;
            arrPar[8] = new SqlParameter("@strUsuarioAlta", SqlDbType.VarChar);
            arrPar[8].Value = obj.strUsuarioAlta;
            arrPar[9] = new SqlParameter("@strMaquinaAlta", SqlDbType.VarChar);
            arrPar[9].Value = obj.strMaquinaAlta;
            arrPar[10] = new SqlParameter("@datFechaMod", SqlDbType.DateTime);
            arrPar[10].Value = obj.datFechaMod;
            arrPar[11] = new SqlParameter("@strUsuarioMod", SqlDbType.VarChar);
            arrPar[11].Value = obj.strUsuarioMod;
            arrPar[12] = new SqlParameter("@strMaquinaMod", SqlDbType.VarChar);
            arrPar[12].Value = obj.strMaquinaMod;
            arrPar[13] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[13].Value = obj.intEmpresa;

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFinRubros_Save", arrPar).ToString();
            }
            catch (Exception e)
            {
                throw e;
            }

            return result;
        }

        #endregion


        #region Delete
        public static string Delete(Entity_EstadosFinRubros obj)
        {

            string result = "";

            SqlParameter[] arrPar = new SqlParameter[3];

            arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
            arrPar[0].Value = obj.intEstadoFin;
            arrPar[1] = new SqlParameter("@intRubro", SqlDbType.Int);
            arrPar[1].Value = obj.intRubro;
            arrPar[2] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[2].Value = obj.intEmpresa;

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFinRubros_Del", arrPar).ToString();
            }
            catch (Exception e)
            {
                throw e;
            }

            return result;
        }

        #endregion Delete  
    }
}
