/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-09-02
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACEdoFinancieros : Base
    {
        #region Sel
        public static DataTable GetList(Entity_EdoFinancieros obj)
        {
            DataSet ds;

            SqlParameter[] arrPar = new SqlParameter[1];
            arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
            arrPar[0].Value = obj.intEstadoFin;
            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFin_Sel", arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion

        #region Fill
        public static Entity_EdoFinancieros Fill(Entity_EdoFinancieros obj)
        {
            IDataReader drd;
            Entity_EdoFinancieros oEntity_Rubros;
            oEntity_Rubros = new Entity_EdoFinancieros();

            try
            {
                SqlParameter[] arrPar = new SqlParameter[1];
                arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
                arrPar[0].Value = obj.intEstadoFin;

                drd = SqlHelper.ExecuteReader(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFin_Sel", arrPar);
                if (drd.Read())
                {
                    oEntity_Rubros = CreateObject(drd);
                }
                else
                {
                    oEntity_Rubros = null;
                }
            }
            catch (Exception e)
            {
                oEntity_Rubros = null;
            }

            return oEntity_Rubros;
        }
        #endregion

        #region Create
        static Entity_EdoFinancieros CreateObject(IDataReader drd)
        {
            Entity_EdoFinancieros obj = new Entity_EdoFinancieros();

            obj.intEstadoFin = Convert.ToInt32(drd["intEstadoFin"].ToString());
            obj.strNombre = drd["strNombre"].ToString();
            obj.strNombreCorto = drd["strNombreCorto"].ToString();
            obj.datFechaAlta = Convert.ToDateTime(drd["datFechaAlta"].ToString());
            obj.strUsuarioAlta = drd["strUsuarioAlta"].ToString();
            obj.strMaquinaAlta = drd["strMaquinaAlta"].ToString();
            obj.datFechaMod = Convert.ToDateTime(drd["datFechaMod"].ToString());
            obj.strUsuarioMod = drd["strUsuarioMod"].ToString();
            obj.strMaquinaMod = drd["strMaquinaMod"].ToString();

            return obj;
        }
        #endregion

        #region Save
        public static string Save(Entity_EdoFinancieros obj)
        {
            string result = "";
            SqlParameter[] arrPar = new SqlParameter[9];

            arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
            arrPar[0].Value = obj.intEstadoFin;
            arrPar[1] = new SqlParameter("@strNombre", SqlDbType.VarChar );
            arrPar[1].Value = obj.strNombre;
            arrPar[2] = new SqlParameter("@strNombreCorto", SqlDbType.VarChar);
            arrPar[2].Value = obj.strNombreCorto;
            arrPar[3] = new SqlParameter("@datFechaAlta", SqlDbType.DateTime );
            arrPar[3].Value = obj.datFechaAlta;
            arrPar[4] = new SqlParameter("@strUsuarioAlta", SqlDbType.VarChar);
            arrPar[4].Value = obj.strUsuarioAlta;
            arrPar[5] = new SqlParameter("@strMaquinaAlta", SqlDbType.VarChar);
            arrPar[5].Value = obj.strMaquinaAlta;
            arrPar[6] = new SqlParameter("@datFechaMod", SqlDbType.DateTime );
            arrPar[6].Value = obj.datFechaMod;
            arrPar[7] = new SqlParameter("@strUsuarioMod", SqlDbType.VarChar);
            arrPar[7].Value = obj.strUsuarioMod;
            arrPar[8] = new SqlParameter("@strMaquinaMod", SqlDbType.VarChar);
            arrPar[8].Value = obj.strMaquinaMod;

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFin_Save", arrPar).ToString();
            }
            catch (Exception e)
            {
                throw e;
            }

            return result;
        }

        #endregion


        #region Delete
        public static string Delete(Entity_EdoFinancieros obj)
        {

            string result = "";

            SqlParameter[] arrPar = new SqlParameter[2];

            arrPar[0] = new SqlParameter("@intEstadoFin", SqlDbType.Int);
            arrPar[0].Value = obj.intEstadoFin;

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "usp_tbEstadosFin_Del", arrPar).ToString();
            }
            catch (Exception e)
            {
                throw e;
            }

            return result;
        }

        #endregion Delete  
  
    }
}
