/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACFacturaDet : Base
	{
        
		#region GetList
        public static DataTable GetList(Entity_Factura obj)
        {
            DataSet ds;

            SqlParameter[] arrPar = new SqlParameter[2];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;
            arrPar[1] = new SqlParameter("@intContraRecibo", SqlDbType.Int);
            arrPar[1].Value = obj.IntContraRecibo;

            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbFacXP_List", arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
		#endregion

        #region Fill
        public static Entity_FacturaDet Fill(Entity_FacturaDet obj)
        {
            IDataReader drd;
            Entity_FacturaDet oEntity_Factura;
            oEntity_Factura = new Entity_FacturaDet();

            SqlParameter[] arrPar = new SqlParameter[3];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;
            arrPar[1] = new SqlParameter("@intProveedor", SqlDbType.Int);
            arrPar[1].Value = obj.IntProveedor;
            arrPar[2] = new SqlParameter("@strNC", SqlDbType.VarChar);
            arrPar[2].Value = obj.StrNC;

            try
            {
                drd = SqlHelper.ExecuteReader(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbFacXPDet_Fill", arrPar);
                if (drd.Read())
                {
                    oEntity_Factura = CreateObject(drd);
                }
                else
                    oEntity_Factura = null; 
            }
            catch (Exception e)
            {
                oEntity_Factura = null;
            }

            return oEntity_Factura;
        }
		#endregion                  

        #region Create
        static Entity_FacturaDet CreateObject(IDataReader drd)
        {
            Entity_FacturaDet obj;
            obj = new Entity_FacturaDet();

            obj.IntProveedor = (int)drd["IntProveedor"];
            obj.DatFecha = (string)drd["DatFecha"];
            obj.StrFactura = (string)drd["StrFactura"];
            obj.IntTipoMovto = (int)drd["intTipoMovto"];
            obj.DblMonto = Convert.ToDecimal(drd["dblMonto"]);
            obj.StrDescripcion = (string)drd["strDescripcion"];
            obj.StrFolio = (string)drd["StrFolio"];

            return obj;
        }
		#endregion
		
		#region Save
        public static string Save(Entity_FacturaDet obj)
        {
            string result = "";
    		
            SqlParameter[] arrPar = new SqlParameter[11];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;
            arrPar[1] = new SqlParameter("@intProveedor", SqlDbType.Int);
            arrPar[1].Value = obj.IntProveedor;
            arrPar[2] = new SqlParameter("@strFactura", SqlDbType.VarChar);
            arrPar[2].Value = obj.StrFactura;
            arrPar[3] = new SqlParameter("@datFecha", SqlDbType.DateTime);
            arrPar[3].Value = obj.DatFecha;
            arrPar[4] = new SqlParameter("@strNC", SqlDbType.VarChar);
            arrPar[4].Value = obj.StrNC;
            arrPar[5] = new SqlParameter("@strFolio", SqlDbType.VarChar);
            arrPar[5].Value = obj.StrFolio;
            arrPar[6] = new SqlParameter("@intMovto", SqlDbType.Int);
            arrPar[6].Value = obj.IntTipoMovto;  
            arrPar[7] = new SqlParameter("@dblTotal", SqlDbType.Decimal);
            arrPar[7].Value = obj.DblMonto;
            arrPar[8] = new SqlParameter("@strDescripcion", SqlDbType.VarChar);
            arrPar[8].Value = obj.StrDescripcion;            
            arrPar[9] = new SqlParameter("@strUsuario", SqlDbType.VarChar);
            arrPar[9].Value = obj.StrUsuario;
            arrPar[10] = new SqlParameter("@strMaquina", SqlDbType.VarChar);
            arrPar[10].Value = obj.StrMaquina;

            try
            {
                result = SqlHelper.ExecuteScalar(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbFacXPDet_Save", arrPar).ToString();
            }
            catch (Exception e)
            {
                throw e;
            }

            return result;
        }
        #endregion

        #region Delete
        public static bool Delete(Entity_FacturaDet obj)
			{

                bool bResult = false;

                SqlParameter[] arrPar = new SqlParameter[4];
                arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
                arrPar[0].Value = obj.IntEmpresa;
                arrPar[1] = new SqlParameter("@intProveedor", SqlDbType.Int);
                arrPar[1].Value = obj.IntProveedor;
                arrPar[2] = new SqlParameter("@strFactura", SqlDbType.VarChar);
                arrPar[2].Value = obj.StrFactura;
                arrPar[3] = new SqlParameter("@strNC", SqlDbType.VarChar);
                arrPar[3].Value = obj.StrNC;

                try
                {
                    SqlHelper.ExecuteNonQuery(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbFacXPDet_Del", arrPar);
                    bResult = false;
                }
                catch (Exception e)
                {
                    throw e;
                }

                return bResult;									
			}

        #endregion Delete

        #region GetListMov
        public static DataTable GetListMov(Entity_FacturaDet obj)
        {
            DataSet ds;

            SqlParameter[] arrPar = new SqlParameter[3];
            arrPar[0] = new SqlParameter("@intEmpresa", SqlDbType.Int);
            arrPar[0].Value = obj.IntEmpresa;
            arrPar[1] = new SqlParameter("@intProveedor", SqlDbType.Int);
            arrPar[1].Value = obj.IntProveedor;
            arrPar[2] = new SqlParameter("@strFactura", SqlDbType.VarChar);
            arrPar[2].Value = obj.StrFactura;

            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, "VetecMarfilAdmin..usp_tbFacXPDet_ListMov", arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion

	}
}