/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using Microsoft.ApplicationBlocks.Data;
using Contabilidad.Entity;

namespace Contabilidad.DataAccess
{
    public class DACMenu : Base
    {                          
        
        #region BindMenu
        public static DataTable BindMenu(int ParentId, int intRol)
        {
            string spName;
            DataSet ds;

            SqlParameter[] arrPar = new SqlParameter[2];
            arrPar[0] = new SqlParameter("@ParentId", SqlDbType.Int);
            arrPar[0].Value = ParentId;
            arrPar[1] = new SqlParameter("@intRol", SqlDbType.Int);
            arrPar[1].Value = intRol;
            try
            {
                spName = "usp_tbMenuConta_Create";
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.StoredProcedure, spName, arrPar);
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                return null;
            }
        }
        #endregion

        #region BindGrid
        public static DataSet BindGrid(string query)
        {
            DataSet ds;

            try
            {
                ds = SqlHelper.ExecuteDataset(ConnectionString, CommandType.Text, query);
                return ds;
            }
            catch (Exception e)
            {
                throw e;
            }
        }
        #endregion

    }
}
