/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Menu : EntityBaseClass
    {

        private string _IdRols;
        private int _IdMenu;
        private string _VcMenu;
        private string _VcPagina;
        private int _IdMenuParent;
        private int _ISort;
        private bool _BActivo;
        private int _IdSysLang;
        private string _VcSysLangShort;         

        #region Properties
        
        #region IdRols

        public String IdRols
        {
            get
            {
                return _IdRols;
            }
            set
            {
                _IdRols = value;
            }
        }

        #endregion IdRols

        #region IdMenu

        public int IdMenu
        {
            get
            {
                return _IdMenu;
            }
            set
            {
                _IdMenu = value;
            }
        }

        #endregion IdMenu

        #region VcMenu

        public string VcMenu
        {
            get
            {
                return _VcMenu;
            }
            set
            {
                _VcMenu = value;
            }
        }

        #endregion VcMenu

        #region VcPagina

        public string VcPagina
        {
            get
            {
                return _VcPagina;
            }
            set
            {
                _VcPagina = value;
            }
        }

        #endregion VcPagina

        #region IdMenuParent
        
        public int IdMenuParent
        {
            get
            {
                return _IdMenuParent;
            }
            set
            {
                _IdMenuParent = value;
            }
        }

        #endregion IdMenuParent

        #region ISort

        public int ISort
        {
            get
            {
                return _ISort;
            }
            set
            {
                _ISort = value;
            }
        }

        #endregion ISort

        #region BActivo

        public bool BActivo
        {
            get
            {
                return _BActivo;
            }
            set
            {
                _BActivo = value;
            }
        }

        #endregion BActivo

        #region IdSysLang

        public int IdSysLang
        {
            get
            {
                return _IdSysLang;
            }
            set
            {
                _IdSysLang = value;
            }
        }

        #endregion IdSysLang

        #region VcSysLangShort

        public string VcSysLangShort
        {
            get
            {
                return _VcSysLangShort;
            }
            set
            {
                _VcSysLangShort = value;
            }
        }

        #endregion VcSysLangShort

        #endregion Properties
  
    }
}
