/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Obra : EntityBaseClass
	{
             
        private int _intEmpresa = 0;
        private int _intSucursal = 0;
        private int _intObra = 0;
        private string _strClave = "";
        private string _strNombre = "";
        private int _intTipoObra = 0;
        private int _intTipoAvance = 0;
        private int _intCentroCosto = 0;
        private double _dblFactorSalarioReal = 0;
        private double _dblPorcentajeIndirectos = 0;
        private DateTime _datFechaInicio = Convert.ToDateTime("01/01/1900");
        private string _strContrato = "";
        private string _strStatus = "";
        private string _strTruncaIndirectos = "";
        private string _strFSR = "";
        private string _strResponsable = "";
        private string _strUsuarioAlta = "";
        private string _strMaquinaAlta = "";
        private DateTime _datFechaAlta = Convert.ToDateTime("01/01/1900");
        private string _strUsuarioMod = "";
        private string _strMaquinaMod = "";
        private DateTime _datFechaMod = Convert.ToDateTime("01/01/1900");
        private string _strNombreCorto = "";
        private double _dblImporte = 0;
        private string _strDireccion = "";
        private string _strContraseña = "";
        private int _intResponsable = 0;
        private string _strUbicacion = "";
        private int _intColonia = 0;
        private int _intCP = 0;
        private int _intManzana = 0;
        private int _intGrupo = 0;
        private string _strProyecto = "";
        private DateTime _datFechaFin = Convert.ToDateTime("01/01/1900");
        private DateTime _datFechaServicios = Convert.ToDateTime("01/01/1900");
        private string _strDuracion = "";
        private int _intGerenteEdificacion = 0;
        private int _intGerenteUrbanizacion = 0;
        private int _intSupervisorObra = 0;
        private int _intResponsableCompras = 0;
        private int _intResponsablePlanos = 0;
        private int _intContratistaAlbanileria = 0;
        private int _intContratistaPlomeria = 0;
        private int _intContratistaElectricidad = 0;
        private int _intContratistaImpermeabiliza = 0;
        private int _intOrdenInicio = 0;
        private int _intTipoVivienda = 0;
        private int _intSector = 0;
        private int _intCliente = 0;
        private int _intUrbanizacion = 0;
        private int _intAlmacen = 0;
        private int _intSubAlmacen = 0;
        private int _intRitmo = 0;
			
		#region Properties

        #region IntObra
        public int IntObra
        {
            get
            {
                return _intObra;
            }
            set
            {
                _intObra = value;
            }
        }
        #endregion 

        #region StrClave
        public string StrClave
        {
            get
            {
                return _strClave;
            }
            set
            {
                _strClave = value;
            }
        }
        #endregion 

        #region StrNombre
        public string StrNombre
		    {
                get
                {
                    return _strNombre;
                }
                set
                {
                    _strNombre = value;
                }
            }
            #endregion 

            #region IntTipoObra
            public int IntTipoObra
        {
            get
            {
                return _intTipoObra;
            }
            set
            {
                _intTipoObra = value;
            }
        }
        #endregion 

        public int IntTipoAvance
        {
            get
            {
                return _intTipoAvance;
            }
            set
            {
                _intTipoAvance = value;
            }
        }

        public int IntCentroCosto
        {
            get
            {
                return _intCentroCosto;
            }
            set
            {
                _intCentroCosto = value;
            }
        }

        public double DblFactorSalarioReal
        {
            get
            {
                return _dblFactorSalarioReal;
            }
            set
            {
                _dblFactorSalarioReal = value;
            }
        }

        public double DblPorcentajeIndirectos
        {
            get
            {
                return _dblPorcentajeIndirectos;
            }
            set
            {
                _dblPorcentajeIndirectos = value;
            }
        }

        public DateTime DatFechaInicio
        {
            get
            {
                return _datFechaInicio;
            }
            set
            {
                _datFechaInicio = value;
            }
        }

        public string StrContrato
        {
            get
            {
                return _strContrato;
            }
            set
            {
                _strContrato = value;
            }
        }

        public string StrStatus
        {
            get
            {
                return _strStatus;
            }
            set
            {
                _strStatus = value;
            }
        }

        public string StrTruncaIndirectos
        {
            get
            {
                return _strTruncaIndirectos;
            }
            set
            {
                _strTruncaIndirectos = value;
            }
        }

        public string StrFSR
        {
            get
            {
                return _strFSR;
            }
            set
            {
                _strFSR = value;
            }
        }

        public string StrResponsable
        {
            get
            {
                return _strResponsable;
            }
            set
            {
                _strResponsable = value;
            }
        }

        public string StrUsuarioAlta
        {
            get
            {
                return _strUsuarioAlta;
            }
            set
            {
                _strUsuarioAlta = value;
            }
        }

        public string StrMaquinaAlta
        {
            get
            {
                return _strMaquinaAlta;
            }
            set
            {
                _strMaquinaAlta = value;
            }
        }

        public DateTime DatFechaAlta
        {
            get
            {
                return _datFechaAlta;
            }
            set
            {
                _datFechaAlta = value;
            }
        }

        public string StrUsuarioMod
        {
            get
            {
                return _strUsuarioMod;
            }
            set
            {
                _strUsuarioMod = value;
            }
        }

        public string StrMaquinaMod
        {
            get
            {
                return _strMaquinaMod;
            }
            set
            {
                _strMaquinaMod = value;
            }
        }

        public DateTime DatFechaMod
        {
            get
            {
                return _datFechaMod;
            }
            set
            {
                _datFechaMod = value;
            }
        }

        public string StrNombreCorto
        {
            get
            {
                return _strNombreCorto;
            }
            set
            {
                _strNombreCorto = value;
            }
        }

        public double DblImporte
        {
            get
            {
                return _dblImporte;
            }
            set
            {
                _dblImporte = value;
            }
        }

        public string StrDireccion
        {
            get
            {
                return _strDireccion;
            }
            set
            {
                _strDireccion = value;
            }
        }

        public string StrContraseña
        {
            get
            {
                return _strContraseña;
            }
            set
            {
                _strContraseña = value;
            }
        }

        public int IntResponsable
        {
            get
            {
                return _intResponsable;
            }
            set
            {
                _intResponsable = value;
            }
        }

        public string StrUbicacion
        {
            get
            {
                return _strUbicacion;
            }
            set
            {
                _strUbicacion = value;
            }
        }

        public int IntColonia
        {
            get
            {
                return _intColonia;
            }
            set
            {
                _intColonia = value;
            }
        }

        public int IntCP
        {
            get
            {
                return _intCP;
            }
            set
            {
                _intCP = value;
            }
        }

        public int IntManzana
        {
            get
            {
                return _intManzana;
            }
            set
            {
                _intManzana = value;
            }
        }

        public int IntGrupo
        {
            get
            {
                return _intGrupo;
            }
            set
            {
                _intGrupo = value;
            }
        }

        public string StrProyecto
        {
            get
            {
                return _strProyecto;
            }
            set
            {
                _strProyecto = value;
            }
        }

        public DateTime DatFechaFin
        {
            get
            {
                return _datFechaFin;
            }
            set
            {
                _datFechaFin = value;
            }
        }

        public DateTime DatFechaServicios
        {
            get
            {
                return _datFechaServicios;
            }
            set
            {
                _datFechaServicios = value;
            }
        }

        public string StrDuracion
        {
            get
            {
                return _strDuracion;
            }
            set
            {
                _strDuracion = value;
            }
        }

        public int IntGerenteEdificacion
        {
            get
            {
                return _intGerenteEdificacion;
            }
            set
            {
                _intGerenteEdificacion = value;
            }
        }

        public int IntGerenteUrbanizacion
        {
            get
            {
                return _intGerenteUrbanizacion;
            }
            set
            {
                _intGerenteUrbanizacion = value;
            }
        }

        public int IntSupervisorObra
        {
            get
            {
                return _intSupervisorObra;
            }
            set
            {
                _intSupervisorObra = value;
            }
        }

        public int IntResponsableCompras
        {
            get
            {
                return _intResponsableCompras;
            }
            set
            {
                _intResponsableCompras = value;
            }
        }

        public int IntResponsablePlanos
        {
            get
            {
                return _intResponsablePlanos;
            }
            set
            {
                _intResponsablePlanos = value;
            }
        }

        public int IntContratistaAlbanileria
        {
            get
            {
                return _intContratistaAlbanileria;
            }
            set
            {
                _intContratistaAlbanileria = value;
            }
        }
        public int IntContratistaPlomeria
        {
            get
            {
                return _intContratistaPlomeria;
            }
            set
            {
                _intContratistaPlomeria = value;
            }
        }

        public int IntContratistaElectricidad
        {
            get
            {
                return _intContratistaElectricidad;
            }
            set
            {
                _intContratistaElectricidad = value;
            }
        }

        public int IntContratistaImpermeabiliza
        {
            get
            {
                return _intContratistaImpermeabiliza;
            }
            set
            {
                _intContratistaImpermeabiliza = value;
            }
        }

        public int IntOrdenInicio
        {
            get
            {
                return _intOrdenInicio;
            }
            set
            {
                _intOrdenInicio = value;
            }
        }

        public int IntTipoVivienda
        {
            get
            {
                return _intTipoVivienda;
            }
            set
            {
                _intTipoVivienda = value;
            }
        }

        public int IntSector
        {
            get
            {
                return _intSector;
            }
            set
            {
                _intSector = value;
            }
        }

        public int IntCliente
        {
            get
            {
                return _intCliente;
            }
            set
            {
                _intCliente = value;
            }
        }

        public int IntUrbanizacion
        {
            get
            {
                return _intUrbanizacion;
            }
            set
            {
                _intUrbanizacion = value;
            }
        }

        public int IntAlmacen
        {
            get
            {
                return _intAlmacen;
            }
            set
            {
                _intAlmacen = value;
            }
        }
        #endregion 

        #region IntSubAlmacen
        public int IntSubAlmacen
        {
            get
            {
                return _intSubAlmacen;
            }
            set
            {
                _intSubAlmacen = value;
            }
        }
        #endregion 


	}
}
