/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Clientes : EntityBaseClass
	{

        private int _intEmpresa;
        private int _intSucursal;
        private int _intCliente;
        private string _strNombre;
        private string _strDireccion;
        private string _strColonia;
        private int _intCP;
        private string _strUsuarioAlta;
        private string _strMaquinaAlta;
        private DateTime _datFechaAlta;
        private string _strUsuarioMod;
        private string _strMaquinaMod;
        private DateTime _datFechaMod;
        private string _strTelefono;
        private string _strRFC;
        private string _strTelefono2;
        private string _strFax;
        private string _strDireccionWeb;
        private int _intDir;
        private int _intProspecto;
        private int _intEstatus;
        private int _intTipo;
        private string _strNombreCorto;
        private string _strClave;
        private int _intEstado;
        private int _intMunicipio;
        private double _dblLimiteCredito;
        private int _intSegmento;
        private int _intTipoMovimientoBase;
        private double _dblDescuento;
        private int _intCondicionesPago;
        private int _intMoneda;
        private int _intReferenciaDeposito;
        private int _intOrigenCliente;
        private string _strResponsable;
        private string _strCC;
        private string _strEmail;

        public int intEmpresa
        {
            get
            {
                return _intEmpresa;
            }
            set
            {
                _intEmpresa = value;
            }
        }

        public int intSucursal
        {
            get
            {
                return _intSucursal;
            }
            set
            {
                _intSucursal = value;
            }
        }

        public int intCliente
        {
            get
            {
                return _intCliente;
            }
            set
            {
                _intCliente = value;
            }
        }

        public string strNombre
        {
            get
            {
                return _strNombre;
            }
            set
            {
                _strNombre = value;
            }
        }

        public string strDireccion
        {
            get
            {
                return _strDireccion;
            }
            set
            {
                _strDireccion = value;
            }
        }

        public string strColonia
        {
            get
            {
                return _strColonia;
            }
            set
            {
                _strColonia = value;
            }
        }

        public int intCP
        {
            get
            {
                return _intCP;
            }
            set
            {
                _intCP = value;
            }
        }

        public string strUsuarioAlta
        {
            get
            {
                return _strUsuarioAlta;
            }
            set
            {
                _strUsuarioAlta = value;
            }
        }

        public string strMaquinaAlta
        {
            get
            {
                return _strMaquinaAlta;
            }
            set
            {
                _strMaquinaAlta = value;
            }
        }

        public DateTime datFechaAlta
        {
            get
            {
                return _datFechaAlta;
            }
            set
            {
                _datFechaAlta = value;
            }
        }

        public string strUsuarioMod
        {
            get
            {
                return _strUsuarioMod;
            }
            set
            {
                _strUsuarioMod = value;
            }
        }

        public string strMaquinaMod
        {
            get
            {
                return _strMaquinaMod;
            }
            set
            {
                _strMaquinaMod = value;
            }
        }

        public DateTime datFechaMod
        {
            get
            {
                return _datFechaMod;
            }
            set
            {
                _datFechaMod = value;
            }
        }

        public string strTelefono
        {
            get
            {
                return _strTelefono;
            }
            set
            {
                _strTelefono = value;
            }
        }

        public string strRFC
        {
            get
            {
                return _strRFC;
            }
            set
            {
                _strRFC = value;
            }
        }

        public string strTelefono2
        {
            get
            {
                return _strTelefono2;
            }
            set
            {
                _strTelefono2 = value;
            }
        }

        public string strFax
        {
            get
            {
                return _strFax;
            }
            set
            {
                _strFax = value;
            }
        }

        public string strDireccionWeb
        {
            get
            {
                return _strDireccionWeb;
            }
            set
            {
                _strDireccionWeb = value;
            }
        }

        public int intDir
        {
            get
            {
                return _intDir;
            }
            set
            {
                _intDir = value;
            }
        }

        public int intProspecto
        {
            get
            {
                return _intProspecto;
            }
            set
            {
                _intProspecto = value;
            }
        }

        public int intEstatus
        {
            get
            {
                return _intEstatus;
            }
            set
            {
                _intEstatus = value;
            }
        }

        public int intTipo
        {
            get
            {
                return _intTipo;
            }
            set
            {
                _intTipo = value;
            }
        }

        public string strNombreCorto
        {
            get
            {
                return _strNombreCorto;
            }
            set
            {
                _strNombreCorto = value;
            }
        }
        
        public string strClave
        {
            get
            {
                return _strClave;
            }
            set
            {
                _strClave = value;
            }
        }

        public int intEstado
        {
            get
            {
                return _intEstado;
            }
            set
            {
                _intEstado = value;
            }
        }

        public int intMunicipio
        {
            get
            {
                return _intMunicipio;
            }
            set
            {
                _intMunicipio = value;
            }
        }


        public double  dblLimiteCredito
        {
            get
            {
                return _dblLimiteCredito;
            }
            set
            {
                _dblLimiteCredito = value;
            }
        }

        public int  intSegmento
        {
            get
            {
                return _intSegmento;
            }
            set
            {
                _intSegmento = value;
            }
        }

        public int intTipoMovimientoBase
        {
            get
            {
                return _intTipoMovimientoBase;
            }
            set
            {
                _intTipoMovimientoBase = value;
            }
        }

        public double dblDescuento
        {
            get
            {
                return _dblDescuento;
            }
            set
            {
                _dblDescuento = value;
            }
        }

        public int intCondicionesPago
        {
            get
            {
                return _intCondicionesPago;
            }
            set
            {
                _intCondicionesPago = value;
            }
        }

        public int intMoneda
        {
            get
            {
                return _intMoneda;
            }
            set
            {
                _intMoneda = value;
            }
        }

        public int intReferenciaDeposito
        {
            get
            {
                return _intReferenciaDeposito;
            }
            set
            {
                _intReferenciaDeposito = value;
            }
        }

        public int intOrigenCliente
        {
            get
            {
                return _intOrigenCliente;
            }
            set
            {
                _intOrigenCliente = value;
            }
        }

        public string strResponsable
        {
            get
            {
                return _strResponsable;
            }
            set
            {
                _strResponsable = value;
            }
        }

        public string strCC
        {
            get
            {
                return _strCC;
            }
            set
            {
                _strCC = value;
            }
        }

        public string strEmail
        {
            get
            {
                return _strEmail;
            }
            set
            {
                _strEmail = value;
            }
        }
     }
}
