/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_TempPoliza_Remplazo : EntityBaseClass
	{
        private int _intEmpresa;
	    private int _intPartida;
        private string _strCuenta;
        private string _strAuxiliar;
        private string _strObra;
        private string _strReferencia;
        private decimal _dblCargos;
        private decimal _dblAbonos;
        private string _strDescricpion;
        private string _strUsuario;
       			
		#region Properties

        #region IntEmpresa
        public int IntEmpresa
		    {
                get
                {
                    return _intEmpresa;
                }
                set
                {
                    _intEmpresa = value;
                }
            }
        #endregion IntEmpresa

        #region IntPartida
            public int IntPartida
		    {
                get
                {
                    return _intPartida;
                }
                set
                {
                    _intPartida = value;
                }
            }
            #endregion IntPartida
        
        #region StrCuenta
            public string StrCuenta
        {
            get
            {
                return _strCuenta;
            }
            set
            {
                _strCuenta = value;
            }
        }
            #endregion StrCuenta
        
        #region StrAuxiliar
        public string StrAuxiliar
        {
            get
            {
                return _strAuxiliar;
            }
            set
            {
                _strAuxiliar = value;
            }
        }
        #endregion StrAuxiliar

        #region StrObra
        public string StrObra
        {
            get
            {
                return _strObra;
            }
            set
            {
                _strObra = value;
            }
        }
        #endregion StrObra
        
        #region StrReferencia
        public string StrReferencia
        {
            get
            {
                return _strReferencia;
            }
            set
            {
                _strReferencia = value;
            }
        }
        #endregion StrReferencia
        
        #region DblCargo
        public decimal DblCargo
        {
            get
            {
                return _dblCargos;
            }
            set
            {
                _dblCargos = value;
            }
        }
        #endregion DblCargos

        #region DblAbono
        public decimal DblAbono
        {
            get
            {
                return _dblAbonos;
            }
            set
            {
                _dblAbonos = value;
            }
        }
        #endregion DblAbono

        #region StrDescricpion
        public string StrDescricpion
        {
            get
            {
                return _strDescricpion;
            }
            set
            {
                _strDescricpion = value;
            }
        }
        #endregion StrDescricpion

        #region StrUsuario
        public string StrUsuario
        {
            get
            {
                return _strUsuario;
            }
            set
            {
                _strUsuario = value;
            }
        }
        #endregion StrUsuario
     
		#endregion

	}
}
