/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Proveedor : EntityBaseClass
	{

		private int _intProveedor;
        private string _strNombre;
        private string _strCCProv;
        private int _intCondicionPago;
        private int _intMovto;
        private string _Email;

        #region IntProveedor
        public int IntProveedor
		    {
                get
                {
                    return _intProveedor;
                }
                set
                {
                    _intProveedor = value;
                }
			}
			#endregion IdStatus

        #region StrNombre
            public string StrNombre
		    {
                get
                {
                    return _strNombre;
                }
                set
                {
                    _strNombre = value;
                }
			}
			#endregion VcStatusName	

        #region IntCondicionPago
        public int IntCondicionPago
            {
                get
                {
                    return _intCondicionPago;
                }
                set
                {
                    _intCondicionPago = value;
                }
            }
            #endregion

        #region StrCCProv
         public string StrCCProv
            {
                get
                {
                    return _strCCProv;
                }
                set
                {
                    _strCCProv = value;
                }
            }
            #endregion	

        #region IntMovto
            public int IntMovto
            {
                get
                {
                    return _intMovto;
                }
                set
                {
                    _intMovto = value;
                }
            }
            #endregion

            #region Email
            public string Email
        {
            get
            {
                return _Email;
            }
            set
            {
                _Email = value;
            }
        }
        #endregion 

	}
}
