/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Referencia : EntityBaseClass
	{

        private int _intReferencia;  
        private string _strNombre;        
			
		#region Properties

        #region IntReferencia
        public int IntReferencia
        {
            get
            {
                return _intReferencia;
            }
            set
            {
                _intReferencia = value;
            }
        }
        #endregion 

        #region StrNombre
        public string StrNombre
		    {
                get
                {
                    return _strNombre;
                }
                set
                {
                    _strNombre = value;
                }
            }
            #endregion 


		#endregion

	}
}
