/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Estados : EntityBaseClass
    {
        private int _intEstado;
        private string _strNombre;
        private string _strNombreCorto;
        private int _intPais;
        private string _strAuditAlta;
        private string _strAuditMod;

        #region Properties

        #region intEstado
        public int intEstado
        {
            get
            {
                return _intEstado;
            }
            set
            {
                _intEstado = value;
            }
        }
        #endregion intEstado

        #region strNombre
        public string  strNombre
        {
            get
            {
                return _strNombre;
            }
            set
            {
                _strNombre = value;
            }
        }
        #endregion strNombre

        #region strNombreCorto
        public string  strNombreCorto
        {
            get
            {
                return _strNombreCorto;
            }
            set
            {
                _strNombreCorto = value;
            }
        }
        #endregion strNombreCorto

        #region intPais
        public int intPais
        {
            get
            {
                return _intPais;
            }
            set
            {
                _intPais = value;
            }
        }
        #endregion intPais

        #region strAuditAlta
        public string strAuditAlta
        {
            get
            {
                return _strAuditAlta;
            }
            set
            {
                _strAuditAlta = value;
            }
        }
        #endregion strAuditAlta

        #region strAuditMod
        public string strAuditMod
        {
            get
            {
                return _strAuditMod;
            }
            set
            {
                _strAuditMod = value;
            }
        }
        #endregion strAuditMod

        #endregion Properties
    }
}
