/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-08-16
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using System.Collections.Specialized;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class CerrarPeriodo
    {
        #region GetList
        public DataTable  GetList(Entity_CerrarPeriodo obj)
        {
            return DACCerrarPeriodo.GetList(obj);
        }
        #endregion 

        #region Save
        public bool Save(Entity_CerrarPeriodo obj)
        {
            return DACCerrarPeriodo.Save(obj);
        }
        #endregion 

        #region Close
        public string Close(Entity_CerrarPeriodo obj)
        {
            return DACCerrarPeriodo.Close(obj);
        }
        #endregion 
    }
}
