/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-08-16
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using System.Collections.Specialized;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class Clientes
    {
        #region Fill
        public Entity_Articulo Fill(int IdUser)
        {
            return DACArticulo.Fill(IdUser);
        }
        #endregion 

        #region Sel
        public DataTable  Sel(Entity_Clientes obj)
        {
            return DACClientes.Sel(obj);
        }
        #endregion 

        #region ExportAnaliticoComprasProv
        public string ExportAnaliticoComprasProv(int intColonia, int intTipoCredito, string FechaIni, string FechaFin, int intEmpresa, int intSucursal)
        {
            string value = "usp_tbClientes_Cartera ";
            value = value + intEmpresa.ToString() + ",";
            value = value + intSucursal.ToString () + ",";
            value = value + intColonia.ToString() + ",";
            value = value + intTipoCredito.ToString() + ",'";
            value = value + FechaIni + "','";
            value = value + FechaFin + "'";

            return value;
        }
        #endregion

        #region ExportSaldo
        public string ExportSaldo(int intEmpresa, string Fecha)
        {
            string value = "usp_tbClientes_rptSaldo ";
            value = value + intEmpresa.ToString() + ",'";
            value = value + Fecha + "'";

            return value;
        }
        #endregion

        #region rptAuxiliarMensualOC
        public string rptAuxiliarMensualOC(int intEmpresa, string strCuenta, DateTime FechaIni, DateTime FechaFin)
        {
            string value = "VetecMarfilAdmin.dbo.usp_INCN5000_Rep_Aux_Mensual_OC ";
            value = value + intEmpresa.ToString() + ",'";
            value = value + strCuenta + "','";
            value = value + FechaIni.Day.ToString("00") + "/" + FechaIni.Month.ToString("00") + "/" + FechaIni.Year + "','";
            value = value + FechaFin.Day.ToString("00") + "/" + FechaFin.Month.ToString("00") + "/" + FechaFin.Year + "'";

            return value;
        }
        #endregion

    }
}
