/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-09-17
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using System.Collections.Specialized;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class Colonia
    {
        #region GetList
        public DataTable GetList()
        {
            return DACColonia.GetList();
        }
        #endregion 

        #region List
        public DataTable List(Entity_Colonia obj)
        {
            return DACColonia.List(obj);
        }
        #endregion

        #region Fill
        public Entity_Colonia Fill(Entity_Colonia obj)
        {
            return DACColonia.Fill(obj);
        }
        #endregion 

        #region Retrieve
        public Entity_Colonia Retrieve(Entity_Colonia obj)
        {
            return DACColonia.Retrieve(obj);
        }
        #endregion 

        #region SiguienteFolio
        public uint SiguienteFolio(Entity_Colonia obj)
        {
            return DACColonia.SiguienteFolio(obj);
        }
        #endregion

        #region Data
        public DataTable Data(Entity_Colonia obj)
        {
            return DACColonia.Data(obj);
        }
        #endregion

        #region Data
        public string Save(Entity_Colonia obj)
        {
            return DACColonia.Save(obj);
        }
        #endregion

        #region Delete
        public bool Delete(Entity_Colonia obj)
        {
            return DACColonia.Delete(obj);
        }
        #endregion
         
        #region Sel
        public Entity_Colonia Sel(Entity_Colonia obj)
        {
            return DACColonia.Sel(obj);
        }
        #endregion
        public string GetColonias(string strObras)
        {
            return DACColonia.GetColonia(strObras);
        }

        public string GetCasas(string strObras)
        {
            return DACColonia.GetCasas(strObras);
        }

    }
}
