/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-08-19
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using System.Collections.Specialized;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class Conciliaciones
    {
        #region GetList
        public DataTable GetList(int intEmpresa)
        {
            return DACConciliaciones.GetList(intEmpresa);
        }
        #endregion 

        #region List
        public DataTable List(Entity_Conciliaciones obj)
        {
            return DACConciliaciones.List(obj);
        }
        #endregion 

        #region TemConciliacion
        public bool  TemConciliacion(Entity_Conciliaciones obj)
        {
            return DACConciliaciones.TemConciliacion(obj);
        }
        #endregion 


        #region Val
        public string Val(Entity_Conciliaciones obj)
        {
            return DACConciliaciones.Val(obj);
        }
        #endregion 

        #region Del
        public bool Del(Entity_Conciliaciones obj)
        {
            return DACConciliaciones.Del(obj);
        }
        #endregion 

        #region MovimientosConciliados
        public string MovimientosConciliados(Entity_Conciliaciones obj)
        {
            string value = "usp_Movimientos_Bancarios_Conciliados ";
            value = value + obj.IntEmpresa.ToString() + ",";
            value = value + obj.intCuentaBancaria.ToString() + ",";
            value = value + obj.IntMes.ToString() + ",";
            value = value + obj.IntEjercicio.ToString();

            return value;
        }
        #endregion

        #region ConciliacionBancaria 
        public string ConciliacionBancaria(Entity_Conciliaciones obj)
        {
            string value = "usp_Movimientos_Transito_Conciliados ";
            value = value + obj.IntEmpresa.ToString() + ",";
            value = value + obj.intCuentaBancaria.ToString() + ",";
            value = value + obj.IntMes.ToString() + ",";
            value = value + obj.IntEjercicio.ToString();

            return value;
        }
        #endregion

        #region TransitoChequera 
        public string TransitoChequera(Entity_Conciliaciones obj)
        {
            string value = "usp_Movimientos_Conciliados ";
            value = value + obj.IntEmpresa.ToString() + ",";
            value = value + obj.intCuentaBancaria.ToString() + ",";
            value = value + obj.IntMes.ToString() + ",";
            value = value + obj.IntEjercicio.ToString() + ",";
            value = value + obj.IntTipoMovto.ToString();

            return value;
        }
        #endregion

        #region TransitoBancario 
        public string TransitoBancario(Entity_Conciliaciones obj)
        {
            string value = "usp_Movimientos_Conciliados ";
            value = value + obj.IntEmpresa.ToString() + ",";
            value = value + obj.intCuentaBancaria.ToString() + ",";
            value = value + obj.IntMes.ToString() + ",";
            value = value + obj.IntEjercicio.ToString() + ",";
            value = value + obj.IntTipoMovto.ToString();

            return value;
        }
        #endregion                 

    }
}
