/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using System.Collections.Specialized;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class OrdenCompraDet
    {      

        #region GetList
        public DataTable GetList(Entity_OrdenCompraDet obj)
        {
            return DACOrdenCompraDet.GetList(obj);                   
        }
        #endregion       

        #region Fill
        public Entity_OrdenCompraDet Fill(Entity_OrdenCompraDet obj)
        {
            return DACOrdenCompraDet.Fill(obj); 
        }
        #endregion  
           
        #region Save
        public string Save(Entity_OrdenCompraDet obj)
        {
            return DACOrdenCompraDet.Save(obj); 
        }
        #endregion

        #region Delete
        public bool Delete(Entity_OrdenCompraDet obj)
        {
            return DACOrdenCompraDet.Delete(obj); 
        }
        #endregion Delete     

    }
}
