/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Alexis Soto Dimas
'  Date: 2013-08-26
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Iva : EntityBaseClass
    {
        private int _intEmpresa;
        private int _intEjercicio;
        private int _intMes;
        private int _intSistema;
        private int _intFolio;
        private DateTime _datFecha;
        private int _intTM;
        private int _intCheque;
        private string _strPoliza;
        private string _strPolizaBanco;
        private string _strCuenta;
        private int _intProveedor;
        private int _intObra;
        private int _intOrdenCompra;
        private string _strFactura;
        private DateTime _datFechaFactura;
        private string _strCuentaIva;
        private Double _dblMontoIva;
        private Double _dblPorcentajeIva;
        private Double _dblTotal;
        private string _strUsuarioAlta;
        private string _strMaquinaAlta;
        private DateTime _datFechaAlta;
        private int _intEjercicioRef;
        private int _intCuentaBancaria;

        #region intEmpresa
        public int intEmpresa
        {
            get
            {
                return _intEmpresa;
            }
            set
            {
                _intEmpresa = value;
            }
        }
        #endregion intEmpresa

        #region intEjercicio
        public int intEjercicio
        {
            get
            {
                return _intEjercicio;
            }
            set
            {
                _intEjercicio = value;
            }
        }
        #endregion intEjercicio

        #region intMes
        public int intMes
        {
            get
            {
                return _intMes;
            }
            set
            {
                _intMes = value;
            }
        }
        #endregion intMes

        #region intSistema
        public int intSistema
        {
            get
            {
                return _intSistema;
            }
            set
            {
                _intSistema = value;
            }
        }
        #endregion intSistema

        #region intFolio
        public int intFolio
        {
            get
            {
                return _intFolio;
            }
            set
            {
                _intFolio = value;
            }
        }
        #endregion intFolio

        #region datFecha
        public DateTime  datFecha
        {
            get
            {
                return _datFecha;
            }
            set
            {
                _datFecha = value;
            }
        }
        #endregion datFecha

        #region intTM
        public int intTM
        {
            get
            {
                return _intTM;
            }
            set
            {
                _intTM = value;
            }
        }
        #endregion intTM

        #region intCheque
        public int intCheque
        {
            get
            {
                return _intCheque;
            }
            set
            {
                _intCheque = value;
            }
        }
        #endregion intCheque

        #region strPoliza
        public string  strPoliza
        {
            get
            {
                return _strPoliza;
            }
            set
            {
                _strPoliza = value;
            }
        }
        #endregion strPoliza

        #region strPolizaBanco
        public string strPolizaBanco
        {
            get
            {
                return _strPolizaBanco;
            }
            set
            {
                _strPolizaBanco = value;
            }
        }
        #endregion strPolizaBanco

        #region strCuenta
        public string strCuenta
        {
            get
            {
                return _strCuenta;
            }
            set
            {
                _strCuenta = value;
            }
        }
        #endregion strCuenta

        #region intProveedor
        public int intProveedor
        {
            get
            {
                return _intProveedor;
            }
            set
            {
                _intProveedor = value;
            }
        }
        #endregion intProveedor

        #region intObra
        public int intObra
        {
            get
            {
                return _intObra;
            }
            set
            {
                _intObra = value;
            }
        }
        #endregion intObra

        #region intOrdenCompra
        public int intOrdenCompra
        {
            get
            {
                return _intOrdenCompra;
            }
            set
            {
                _intOrdenCompra = value;
            }
        }
        #endregion intOrdenCompra

        #region strFactura
        public string  strFactura
        {
            get
            {
                return _strFactura;
            }
            set
            {
                _strFactura = value;
            }
        }
        #endregion strFactura

        #region datFechaFactura
        public DateTime   datFechaFactura
        {
            get
            {
                return _datFechaFactura;
            }
            set
            {
                _datFechaFactura = value;
            }
        }
        #endregion datFechaFactura

        #region strCuentaIva
        public string  strCuentaIva
        {
            get
            {
                return _strCuentaIva;
            }
            set
            {
                _strCuentaIva = value;
            }
        }
        #endregion strCuentaIva

        #region dblMontoIva
        public Double  dblMontoIva
        {
            get
            {
                return _dblMontoIva;
            }
            set
            {
                _dblMontoIva = value;
            }
        }
        #endregion dblMontoIva

        #region dblPorcentajeIva
        public Double  dblPorcentajeIva
        {
            get
            {
                return _dblPorcentajeIva;
            }
            set
            {
                _dblPorcentajeIva = value;
            }
        }
        #endregion dblPorcentajeIva

        #region dblTotal
        public Double  dblTotal
        {
            get
            {
                return _dblTotal;
            }
            set
            {
                _dblTotal = value;
            }
        }
        #endregion dblTotal

        #region strUsuarioAlta
        public string strUsuarioAlta
        {
            get
            {
                return _strUsuarioAlta;
            }
            set
            {
                _strUsuarioAlta = value;
            }
        }
        #endregion strUsuarioAlta

        #region strMaquinaAlta
        public string strMaquinaAlta
        {
            get
            {
                return _strMaquinaAlta;
            }
            set
            {
                _strMaquinaAlta = value;
            }
        }
        #endregion strMaquinaAlta

        #region datFechaAlta
        public DateTime  datFechaAlta
        {
            get
            {
                return _datFechaAlta;
            }
            set
            {
                _datFechaAlta = value;
            }
        }
        #endregion datFechaAlta

        #region intEjercicioRef
        public int intEjercicioRef
        {
            get
            {
                return _intEjercicioRef;
            }
            set
            {
                _intEjercicioRef = value;
            }
        }
        #endregion intEjercicioRef

        #region intCuentaBancaria
        public int intCuentaBancaria
        {
            get
            {
                return _intCuentaBancaria;
            }
            set
            {
                _intCuentaBancaria = value;
            }
        }
        #endregion intCuentaBancaria

    }
}
