/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_FacturaDet : EntityBaseClass
	{        	
        private int _intProveedor;
        private string _strFactura;
        private int _intTipoMovto;
        private string _strDescripcion;
        private int _strReferencia;
        private decimal _dblMonto;
		private int _intTipoMoneda;
        private int _intCuentaBancaria;
        private string _datFecha;
        private string _datFechaMovimiento;
        private string _datFechaVencimiento;
        private int _lngConsecutivoPago;
        private int _intEjercicioPol;
        private string _strNC;
        private string _strFolio;
			
        #region IntProveedor
        public int IntProveedor
        {
            get
            {
                return _intProveedor;
            }
            set
            {
                _intProveedor = value;
            }
        }
        #endregion IntSector

        #region StrFactura
        public string StrFactura
		    {
                get
                {
                    return _strFactura;
                }
                set
                {
                    _strFactura = value;
                }
            }
        #endregion IntManzana

        #region IntTipoMovto
            public int IntTipoMovto
        {
            get
            {
                return _intTipoMovto;
            }
            set
            {
                _intTipoMovto = value;
            }
        }
            #endregion IntLote

        #region StrDescripcion
        public string StrDescripcion
		    {
                get
                {
                    return _strDescripcion;
                }
                set
                {
                    _strDescripcion = value;
                }
			}
			#endregion VcRolName

        #region DblMonto
        public decimal DblMonto
		    {
                get
                {
                    return _dblMonto;
                }
                set
                {
                    _dblMonto = value;
                }
            }
            #endregion DblMonto

        #region StrReferencia
        public int StrReferencia
        {
            get
            {
                return _strReferencia;
            }
            set
            {
                _strReferencia = value;
            }
        }
        #endregion 

        #region IntTipoMoneda
        public int IntTipoMoneda
            {
                get
                {
                    return _intTipoMoneda;
                }
                set
                {
                    _intTipoMoneda = value;
                }
            }
            #endregion IntManzana

        #region IntCuentaBancaria
        public int IntCuentaBancaria
        {
            get
            {
                return _intCuentaBancaria;
            }
            set
            {
                _intCuentaBancaria = value;
            }
        }
        #endregion

        #region DatFecha
        public string DatFecha
            {
                get
                {
                    return _datFecha;
                }
                set
                {
                    _datFecha = value;
                }
            }
            #endregion VcRolName

        #region DatFechaMovimiento
        public string DatFechaMovimiento
        {
            get
            {
                return _datFechaMovimiento;
            }
            set
            {
                _datFechaMovimiento = value;
            }
        }
        #endregion

        #region DatFechaVencimiento
        public string DatFechaVencimiento
        {
            get
            {
                return _datFechaVencimiento;
            }
            set
            {
                _datFechaVencimiento = value;
            }
        }
        #endregion IntManzana

        #region LngConsecutivoPago
        public int LngConsecutivoPago
        {
            get
            {
                return _lngConsecutivoPago;
            }
            set
            {
                _lngConsecutivoPago = value;
            }
        }
        #endregion

        #region IntEjercicioPol
        public int IntEjercicioPol
        {
            get
            {
                return _intEjercicioPol;
            }
            set
            {
                _intEjercicioPol = value;
            }
        }
        #endregion VcRolName  
     
        #region StrNC
        public string StrNC
        {
            get
            {
                return _strNC;
            }
            set
            {
                _strNC = value;
            }
        }
        #endregion StrNC

        #region StrFolio
        public string StrFolio
        {
            get
            {
                return _strFolio;
            }
            set
            {
                _strFolio = value;
            }
        }
        #endregion StrFolio


    }
}
