/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Usuarios : EntityBaseClass
	{

        private string _strUsuario;
        private string _strNombre;
        private string _strEmail;
        private int _intPerfil;
        private string _strNombrePerfil;
        private string _strPassword;
		
		#region Properties
		
            #region StrUsuario
            public string StrUsuario
		    {
                get
                {
                    return _strUsuario;
                }
                set
                {
                    _strUsuario = value;
                }
			}
			#endregion strClave

            #region StrNombre
            public string StrNombre
		    {
                get
                {
                    return _strNombre;
                }
                set
                {
                    _strNombre = value;
                }
			}
			#endregion Nombre

			#region StrEmail
			public string StrEmail
		    {
                get
                {
                    return _strEmail;
                }
                set
                {
                    _strEmail = value;
                }
			}
			#endregion strEmail

			#region IntRol
        public int IntPerfil
		    {
                get
                {
                    return _intPerfil;
                }
                set
                {
                    _intPerfil = value;
                }
			}
			#endregion IntRol			

            #region StrNombrePerfil
            public string StrNombrePerfil
            {
                get
                {
                    return _strNombrePerfil;
                }
                set
                {
                    _strNombrePerfil = value;
                }
            }
            #endregion StrNombreRol

            #region StrPassword
            public string StrPassword
        {
            get
            {
                return _strPassword;
            }
            set
            {
                _strPassword = value;
            }
        }
            #endregion StrPassword

        #endregion

    }
}
