/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Articulo : EntityBaseClass
	{


        private double _dblCosto;
        private double _dblExistencia;
        private double _dblFactorConversionAlmacenamiento;
        private double _dblFactorConversionCompra;
        private double _dblFactorConversionConsumo;
        private double _dblFactorConversionPresupuesto;
        private double _dblMaximo;
        private double _dblMinimo;
        private double _dblPeso;
        private double _dblPlanta;
        private double _DblPuntoReorden;
        private double _dblTolerancia;
        private double _dblToleranciaCantidadOPorcentaje;
        private double _dblVenta;
        private double _dblVolumen;
        private int _intArticulo;
        private int _intAutorizado;
        private int _intCodigoBarras;
        private int _intEstatus;
        private int _intFacturable;
        private int _intFamilia;
        private int _intGrupo;
        private int _intInventariado;
        private int _intMateriaPrima;
        private int _intOrigen;
        private int _intProductoTerminado;
        private int _intResurtimientoAutomatico;
        private int _intRutaProduccion;
        private int _intSubGrupo;
        private int _intUnidadMedidaAlmacenamiento;
        private int _intUnidadMedidaCompra;
        private int _intUnidadMedidaConsumo;
        private int _intUnidadMedidaPresupuesto;
        private int _intUnidadMedidaVenta;
        private int _intConsecutivo;
        private string _strDescripcion;
        private string _strFamilia;
        private string _strGrupo;
        private string _strImagen;
        private string _strNombre;
        private string _strNombreCorto;
        private string _strSubGrupo;
        private string _strTiempoEntrega;
        private string _strUnidadMedidaAlmacenamiento;
        private string _strUnidadMedidaCompra;
        private string _strUnidadMedidaPresupuesto;
        private string _strUnidadMedidaVenta;
        private string _strUsuarioAutorizo;
        private string _strUsuarioElaboro;
        private string _strUsuarioReviso;
        private int _intObra;
        private string _Unidad;
        private double _dblPrecioPermitido;
        private double _dblCantidadPermitida;

        public double DblCosto
        {
            get
            {
                return _dblCosto;
            }
            set
            {
                _dblCosto = value;
            }
        }

        public double DblExistencia
        {
            get
            {
                return _dblExistencia;
            }
            set
            {
                _dblExistencia = value;
            }
        }

        public double DblFactorConversionAlmacenamiento
        {
            get
            {
                return _dblFactorConversionAlmacenamiento;
            }
            set
            {
                _dblFactorConversionAlmacenamiento = value;
            }
        }

        public double DblFactorConversionCompra
        {
            get
            {
                return _dblFactorConversionCompra;
            }
            set
            {
                _dblFactorConversionCompra = value;
            }
        }

        public double DblFactorConversionConsumo
        {
            get
            {
                return _dblFactorConversionConsumo;
            }
            set
            {
                _dblFactorConversionConsumo = value;
            }
        }

        public double DblFactorConversionPresupuesto
        {
            get
            {
                return _dblFactorConversionPresupuesto;
            }
            set
            {
                _dblFactorConversionPresupuesto = value;
            }
        }

        public double DblMaximo
        {
            get
            {
                return _dblMaximo;
            }
            set
            {
                _dblMaximo = value;
            }
        }

        public double DblMinimo
        {
            get
            {
                return _dblMinimo;
            }
            set
            {
                _dblMinimo = value;
            }
        }

        public double DblPeso
        {
            get
            {
                return _dblPeso;
            }
            set
            {
                _dblPeso = value;
            }
        }

        public double DblPlanta
        {
            get
            {
                return _dblPlanta;
            }
            set
            {
                _dblPlanta = value;
            }
        }

        public double DblPuntoReorden
        {
            get
            {
                return _DblPuntoReorden;
            }
            set
            {
                _DblPuntoReorden = value;
            }
        }

        public double DblTolerancia
        {
            get
            {
                return _dblTolerancia;
            }
            set
            {
                _dblTolerancia = value;
            }
        }

        public double DblToleranciaCantidadOPorcentaje
        {
            get
            {
                return _dblToleranciaCantidadOPorcentaje;
            }
            set
            {
                _dblToleranciaCantidadOPorcentaje = value;
            }
        }

        public double DblVenta
        {
            get
            {
                return _dblVenta;
            }
            set
            {
                _dblVenta = value;
            }
        }

        public double DblVolumen
        {
            get
            {
                return _dblVolumen;
            }
            set
            {
                _dblVolumen = value;
            }
        }

        public int IntArticulo
        {
            get
            {
                return _intArticulo;
            }
            set
            {
                _intArticulo = value;
            }
        }

        public int IntAutorizado
        {
            get
            {
                return _intAutorizado;
            }
            set
            {
                _intAutorizado = value;
            }
        }

        public int IntCodigoBarras
        {
            get
            {
                return _intCodigoBarras;
            }
            set
            {
                _intCodigoBarras = value;
            }
        }

        public int IntEstatus
        {
            get
            {
                return _intEstatus;
            }
            set
            {
                _intEstatus = value;
            }
        }

        public int IntFacturable
        {
            get
            {
                return _intFacturable;
            }
            set
            {
                _intFacturable = value;
            }
        }

        public int IntFamilia
        {
            get
            {
                return _intFamilia;
            }
            set
            {
                _intFamilia = value;
            }
        }

        public int IntGrupo
        {
            get
            {
                return _intGrupo;
            }
            set
            {
                _intGrupo = value;
            }
        }

        public int IntInventariado
        {
            get
            {
                return _intInventariado;
            }
            set
            {
                _intInventariado = value;
            }
        }

        public int IntMateriaPrima
        {
            get
            {
                return _intMateriaPrima;
            }
            set
            {
                _intMateriaPrima = value;
            }
        }

        public int IntOrigen
        {
            get
            {
                return _intOrigen;
            }
            set
            {
                _intOrigen = value;
            }
        }

        public int IntProductoTerminado
        {
            get
            {
                return _intProductoTerminado;
            }
            set
            {
                _intProductoTerminado = value;
            }
        }

        public int IntResurtimientoAutomatico
        {
            get
            {
                return _intResurtimientoAutomatico;
            }
            set
            {
                _intResurtimientoAutomatico = value;
            }
        }

        public int IntRutaProduccion
        {
            get
            {
                return _intRutaProduccion;
            }
            set
            {
                _intRutaProduccion = value;
            }
        }

        public int IntSubGrupo
        {
            get
            {
                return _intSubGrupo;
            }
            set
            {
                _intSubGrupo = value;
            }
        }

        public int IntUnidadMedidaAlmacenamiento
        {
            get
            {
                return _intUnidadMedidaAlmacenamiento;
            }
            set
            {
                _intUnidadMedidaAlmacenamiento = value;
            }
        }

        public int IntUnidadMedidaCompra
        {
            get
            {
                return _intUnidadMedidaCompra;
            }
            set
            {
                _intUnidadMedidaCompra = value;
            }
        }

        public int IntUnidadMedidaConsumo
        {
            get
            {
                return _intUnidadMedidaConsumo;
            }
            set
            {
                _intUnidadMedidaConsumo = value;
            }
        }

        public int IntUnidadMedidaPresupuesto
        {
            get
            {
                return _intUnidadMedidaPresupuesto;
            }
            set
            {
                _intUnidadMedidaPresupuesto = value;
            }
        }

        public int IntUnidadMedidaVenta
        {
            get
            {
                return _intUnidadMedidaVenta;
            }
            set
            {
                _intUnidadMedidaVenta = value;
            }
        }

        public string StrDescripcion
        {
            get
            {
                return _strDescripcion;
            }
            set
            {
                _strDescripcion = value;
            }
        }

        public string StrFamilia
        {
            get
            {
                return _strFamilia;
            }
            set
            {
                _strFamilia = value;
            }
        }

        public string StrGrupo
        {
            get
            {
                return _strGrupo;
            }
            set
            {
                _strGrupo = value;
            }
        }

        public string StrImagen
        {
            get
            {
                return _strImagen;
            }
            set
            {
                _strImagen = value;
            }
        }

        public string StrNombre
        {
            get
            {
                return _strNombre;
            }
            set
            {
                _strNombre = value;
            }
        }

        public string StrNombreCorto
        {
            get
            {
                return _strNombreCorto;
            }
            set
            {
                _strNombreCorto = value;
            }
        }

        public string StrSubGrupo
        {
            get
            {
                return _strSubGrupo;
            }
            set
            {
                _strSubGrupo = value;
            }
        }

        public string StrTiempoEntrega
        {
            get
            {
                return _strTiempoEntrega;
            }
            set
            {
                _strTiempoEntrega = value;
            }
        }

        public string strUnidadMedidaAlmacenamiento
        {
            get
            {
                return _strUnidadMedidaAlmacenamiento;
            }
            set
            {
                _strUnidadMedidaAlmacenamiento = value;
            }
        }

        public string strUnidadMedidaCompra
        {
            get
            {
                return _strUnidadMedidaCompra;
            }
            set
            {
                _strUnidadMedidaCompra = value;
            }
        }

        public string strUnidadMedidaPresupuesto
        {
            get
            {
                return _strUnidadMedidaPresupuesto;
            }
            set
            {
                _strUnidadMedidaPresupuesto = value;
            }
        }

        public string strUnidadMedidaVenta
        {
            get
            {
                return _strUnidadMedidaVenta;
            }
            set
            {
                _strUnidadMedidaVenta = value;
            }
        }

        public string StrUsuarioAutorizo
        {
            get
            {
                return _strUsuarioAutorizo;
            }
            set
            {
                _strUsuarioAutorizo = value;
            }
        }

        public string StrUsuarioElaboro
        {
            get
            {
                return _strUsuarioElaboro;
            }
            set
            {
                _strUsuarioElaboro = value;
            }
        }

        public string StrUsuarioReviso
        {
            get
            {
                return _strUsuarioReviso;
            }
            set
            {
                _strUsuarioReviso = value;
            }
        }

        public int IntConsecutivo
        {
            get
            {
                return _intConsecutivo;
            }
            set
            {
                _intConsecutivo = value;
            }
        }

        public int IntObra
        {
            get
            {
                return _intObra;
            }
            set
            {
                _intObra = value;
            }
        }


        public string Unidad
        {
            get
            {
                return _Unidad;
            }
            set
            {
                _Unidad = value;
            }
        }

        public double DblPrecioPermitido
        {
            get
            {
                return _dblPrecioPermitido;
            }
            set
            {
                _dblPrecioPermitido = value;
            }
        }

        public double DblCantidadPermitida
        {
            get
            {
                return _dblCantidadPermitida;
            }
            set
            {
                _dblCantidadPermitida = value;
            }
        }
	}
}
