/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_TipoMovimiento : EntityBaseClass
	{

		private int _intTipoMovto;
        private string _strNombre;

        private int _intEmpresa;
        private int _intMovto;
        private string _strAuditAlta;
        private string _strAuditMod;
        private string _strNaturaleza;
        private bool _bFactura;

        #region IntTipoMovto
        public int IntTipoMovto
		    {
                get
                {
                    return _intTipoMovto;
                }
                set
                {
                    _intTipoMovto = value;
                }
			}
			#endregion IdStatus

        #region StrNombre
            public string StrNombre
		    {
                get
                {
                    return _strNombre;
                }
                set
                {
                    _strNombre = value;
                }
			}
			#endregion VcStatusName	


        #region IntEmpresa
        public int IntEmpresa
        {
            get
            {
                return _intEmpresa;
            }
            set
            {
                _intEmpresa = value;
            }
        }
        #endregion IntEmpresa

        #region IntMovto
        public int IntMovto
        {
            get
            {
                return _intMovto;
            }
            set
            {
                _intMovto = value;
            }
        }
        #endregion IntMovto

        #region StrAuditAlta
        public string StrAuditAlta
        {
            get
            {
                return _strAuditAlta;
            }
            set
            {
                _strAuditAlta = value;
            }
        }
        #endregion StrAuditAlta

        #region StrAuditMod
        public string StrAuditMod
        {
            get
            {
                return _strAuditMod;
            }
            set
            {
                _strAuditMod = value;
            }
        }
        #endregion StrAuditMod

        #region StrNaturaleza
        public string StrNaturaleza
        {
            get
            {
                return _strNaturaleza;
            }
            set
            {
                _strNaturaleza = value;
            }
        }
        #endregion StrNaturaleza

        #region BFactura
        public bool BFactura
        {
            get
            {
                return _bFactura;
            }
            set
            {
                _bFactura = value;
            }
        }
        #endregion BFactura
	}
}
