/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Empresa : EntityBaseClass
	{
        
        private int _intEmpresa;
        private string _strNombre="";
        private string _strNombreCorto = "";
        private string _strDireccion = "";
        private string _strColonia = "";
        private string _strRfc = "";

        private int _intGrupo = 0;
        private string _strDelegacion = "";
        private int _intEstado =0;
        private int _intCiudad = 0;
        private string _strRegImss = "";
        private string _strCodigoPostal = "";
        private string _strResponsable = "";
        private string _strRfcResponsable = "";
        private int _intTipoMoneda = 0;
        private int _intLogo = 0;
        private DateTime _datFechaAlta = Convert.ToDateTime ( "01/01/1900");
        private string _strUsuarioAlta = "";
        private string _strMaquinaAlta = "";
        private DateTime _datFechaMod = Convert.ToDateTime ("01/01/1900");
        private string _strUsuarioMod = "";
        private string _strMaquinaMod = "";
        private double _dblInteresMoratorio=0;
			
		#region Properties

        #region IntEmpresa
        public int IntEmpresa
		    {
                get
                {
                    return _intEmpresa;
                }
                set
                {
                    _intEmpresa = value;
                }
            }
        #endregion IntEmpresa

        #region StrNombre
            public string StrNombre
		    {
                get
                {
                    return _strNombre;
                }
                set
                {
                    _strNombre = value;
                }
            }
            #endregion StrNombre

        #region StrNombreCorto
        public string StrNombreCorto
        {
            get
            {
                return _strNombreCorto;
            }
            set
            {
                _strNombreCorto = value;
            }
        }
            #endregion StrNombreCorto

        #region StrDireccion
        public string StrDireccion
        {
            get
            {
                return _strDireccion;
            }
            set
            {
                _strDireccion = value;
            }
        }
        #endregion StrDireccion

        #region StrColonia
        public string StrColonia
        {
            get
            {
                return _strColonia;
            }
            set
            {
                _strColonia = value;
            }
        }
        #endregion StrNombre

        #region StrRfc
        public string StrRfc
        {
            get
            {
                return _strRfc;
            }
            set
            {
                _strRfc = value;
            }
        }
        #endregion StrRfc      

        #region intGrupo
        public int intGrupo
        {
            get
            {
                return _intGrupo;
            }
            set
            {
                _intGrupo = value;
            }
        }
        #endregion intGrupo

        #region strDelegacion
        public string strDelegacion
        {
            get
            {
                return _strDelegacion;
            }
            set
            {
                _strDelegacion = value;
            }
        }
        #endregion strDelegacion

        #region intEstado
        public int intEstado
        {
            get
            {
                return _intEstado;
            }
            set
            {
                _intEstado = value;
            }
        }
        #endregion intEstado

        #region intCiudad
        public int intCiudad
        {
            get
            {
                return _intCiudad;
            }
            set
            {
                _intCiudad = value;
            }
        }
        #endregion intCiudad

        #region strRegImss
        public string strRegImss
        {
            get
            {
                return _strRegImss;
            }
            set
            {
                _strRegImss = value;
            }
        }
        #endregion strRegImss

        #region strCodigoPostal
        public string strCodigoPostal
        {
            get
            {
                return _strCodigoPostal;
            }
            set
            {
                _strCodigoPostal = value;
            }
        }
        #endregion strCodigoPostal

        #region strResponsable
        public string strResponsable
        {
            get
            {
                return _strResponsable;
            }
            set
            {
                _strResponsable = value;
            }
        }
        #endregion strResponsable

        #region strRfcResponsable
        public string strRfcResponsable
        {
            get
            {
                return _strRfcResponsable;
            }
            set
            {
                _strRfcResponsable = value;
            }
        }
        #endregion strRfcResponsable

        #region intTipoMoneda
        public int intTipoMoneda
        {
            get
            {
                return _intTipoMoneda;
            }
            set
            {
                _intTipoMoneda = value;
            }
        }
        #endregion intTipoMoneda

        #region intLogo
        public int intLogo
        {
            get
            {
                return _intLogo;
            }
            set
            {
                _intLogo = value;
            }
        }
        #endregion intLogo

        #region datFechaAlta
        public DateTime  datFechaAlta
        {
            get
            {
                return _datFechaAlta;
            }
            set
            {
                _datFechaAlta = value;
            }
        }
        #endregion datFechaAlta

        #region strUsuarioAlta
        public string strUsuarioAlta
        {
            get
            {
                return _strUsuarioAlta;
            }
            set
            {
                _strUsuarioAlta = value;
            }
        }
        #endregion strUsuarioAlta

        #region strMaquinaAlta
        public string strMaquinaAlta
        {
            get
            {
                return _strMaquinaAlta;
            }
            set
            {
                _strMaquinaAlta = value;
            }
        }
        #endregion strMaquinaAlta

        #region datFechaMod
        public DateTime datFechaMod
        {
            get
            {
                return _datFechaMod;
            }
            set
            {
                _datFechaMod = value;
            }
        }
        #endregion datFechaMod

        #region strUsuarioMod
        public string strUsuarioMod
        {
            get
            {
                return _strUsuarioMod;
            }
            set
            {
                _strUsuarioMod = value;
            }
        }
        #endregion strUsuarioMod

        #region strMaquinaMod
        public string strMaquinaMod
        {
            get
            {
                return _strMaquinaMod;
            }
            set
            {
                _strMaquinaMod = value;
            }
        }
        #endregion strMaquinaMod


        #region dblInteresMoratorio
        public double dblInteresMoratorio
        {
            get
            {
                return _dblInteresMoratorio;
            }
            set
            {
                _dblInteresMoratorio = value;
            }
        }
        #endregion dblInteresMoratorio

		#endregion

	}
}
