/*
'===============================================================================
'  Company: ISD
'  Autor: Ingrid Soto Dimas
'  Date: 2013-06-19
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_CuentasBancarias : EntityBaseClass
    {

        private int _intEmpresa;
        private int _intCuentaBancaria;
        private int _intBanco;
        private string _strNombre = string.Empty;
        private string _strSucursal = string.Empty;
        private string _strNumCuenta = string.Empty;
        private string _strCCBanco = string.Empty;
        private string _strCCComplem = string.Empty;
        private string _strCCTransferencia = string.Empty;
        private string _strTipoPoliza = string.Empty;
        private int _intTipoMoneda;
        private int _intIdioma;
        private int _intFolio;
        private int _intFolioTransferencia;
        private double _dblSaldo;
        private string _strUsuarioAlta = string.Empty;
        private string _strMaquinaAlta = string.Empty;
        private DateTime _datFechaAlta = Convert.ToDateTime("01/01/1900");
        private string _strUsuarioMod = string.Empty;
        private string _strMaquinaMod = string.Empty;
        private DateTime _datFechaMod = Convert.ToDateTime("01/01/1900");
        private string _strCCBancoOrig = string.Empty;
        private string _strCCComplemOrig = string.Empty;
        private string _strReporte = string.Empty;
        private int _intPoliza;
        private int _intProveedor;


        #region Properties

        #region IntEmpresa
        public int IntEmpresa
        {
            get
            {
                return _intEmpresa;
            }
            set
            {
                _intEmpresa = value;
            }
        }
        #endregion IntEmpresa


        #region intCuentaBancaria
        public int intCuentaBancaria
        {
            get
            {
                return _intCuentaBancaria;
            }
            set
            {
                _intCuentaBancaria = value;
            }
        }
        #endregion intCuentaBancaria

        #region intBanco
        public int intBanco
        {
            get
            {
                return _intBanco;
            }
            set
            {
                _intBanco = value;
            }
        }
        #endregion intBanco


        #region strNombre

        public string strNombre
        {
            get
            {
                return _strNombre;
            }
            set
            {
                _strNombre = value;
            }
        }

        #endregion strSucursal

        #region strSucursal
        public string strSucursal
        {
            get
            {
                return _strSucursal;
            }
            set
            {
                _strSucursal = value;
            }
        }
        #endregion strSucursal

        #region strNumCuenta
        public string strNumCuenta
        {
            get
            {
                return _strNumCuenta;
            }
            set
            {
                _strNumCuenta = value;
            }
        }
        #endregion strNumCuenta


        #region strCCBanco
        public string strCCBanco
        {
            get
            {
                return _strCCBanco;
            }
            set
            {
                _strCCBanco = value;
            }
        }
        #endregion strCCBanco

        #region strCCComplem
        public string strCCComplem
        {
            get
            {
                return _strCCComplem;
            }
            set
            {
                _strCCComplem = value;
            }
        }
        #endregion strCCComplem


        #region strCCTransferencia
        public string strCCTransferencia
        {
            get
            {
                return _strCCTransferencia;
            }
            set
            {
                _strCCTransferencia = value;
            }
        }
        #endregion strCCTransferencia

        #region strTipoPoliza
        public string strTipoPoliza
        {
            get
            {
                return _strTipoPoliza;
            }
            set
            {
                _strTipoPoliza = value;
            }
        }
        #endregion strTipoPoliza

        #region intTipoMoneda
        public int intTipoMoneda
        {
            get
            {
                return _intTipoMoneda;
            }
            set
            {
                _intTipoMoneda = value;
            }
        }
        #endregion intTipoMoneda

        #region intIdioma
        public int intIdioma
        {
            get
            {
                return _intIdioma;
            }
            set
            {
                _intIdioma = value;
            }
        }
        #endregion intIdioma

        #region intFolio
        public int intFolio
        {
            get
            {
                return _intFolio;
            }
            set
            {
                _intFolio = value;
            }
        }
        #endregion intFolio

        #region intFolioTransferencia
        public int intFolioTransferencia
        {
            get
            {
                return _intFolioTransferencia;
            }
            set
            {
                _intFolioTransferencia = value;
            }
        }
        #endregion intFolioTransferencia

        #region dblSaldo
        public double dblSaldo
        {
            get
            {
                return _dblSaldo;
            }
            set
            {
                _dblSaldo = value;
            }
        }
        #endregion dblSaldo

        #region strUsuarioAlta
        public string strUsuarioAlta
        {
            get
            {
                return _strUsuarioAlta;
            }
            set
            {
                _strUsuarioAlta = value;
            }
        }
        #endregion strUsuarioAlta


        #region strMaquinaAlta
        public string strMaquinaAlta
        {
            get
            {
                return _strMaquinaAlta;
            }
            set
            {
                _strMaquinaAlta = value;
            }
        }
        #endregion strMaquinaAlta

        #region datFechaAlta
        public DateTime datFechaAlta
        {
            get
            {
                return _datFechaAlta;
            }
            set
            {
                _datFechaAlta = value;
            }
        }
        #endregion datFechaAlta

        #region strUsuarioMod
        public string strUsuarioMod
        {
            get
            {
                return _strUsuarioMod;
            }
            set
            {
                _strUsuarioMod = value;
            }
        }
        #endregion strUsuarioMod


        #region strMaquinaMod
        public string strMaquinaMod
        {
            get
            {
                return _strMaquinaMod;
            }
            set
            {
                _strMaquinaMod = value;
            }
        }
        #endregion strMaquinaMod

        #region datFechaMod
        public DateTime datFechaMod
        {
            get
            {
                return _datFechaMod;
            }
            set
            {
                _datFechaMod = value;
            }
        }
        #endregion datFechaMod

        #region strCCBancoOrig
        public string strCCBancoOrig
        {
            get
            {
                return _strCCBancoOrig;
            }
            set
            {
                _strCCBancoOrig = value;
            }
        }
        #endregion strCCBancoOrig

        #region strCCComplemOrig
        public string strCCComplemOrig
        {
            get
            {
                return _strCCComplemOrig;
            }
            set
            {
                _strCCComplemOrig = value;
            }
        }
        #endregion strCCComplemOrig


        #region strReporte
        public string strReporte
        {
            get
            {
                return _strReporte;
            }
            set
            {
                _strReporte = value;
            }
        }
        #endregion strReporte

        #region intPoliza
        public int intPoliza
        {
            get
            {
                return _intPoliza;
            }
            set
            {
                _intPoliza = value;
            }
        }
        #endregion intPoliza


        #region intProveedor
        public int intProveedor
        {
            get
            {
                return _intProveedor;
            }
            set
            {
                _intProveedor = value;
            }
        }
        #endregion intProveedor


        #endregion

    }
}
