/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Collections.Generic;
using System.Text;

namespace Contabilidad.Entity
{
    public class EntityBaseClass 
    {
        private int _SortDirection = 1; //1 = Ascendiente; 0 = descendiente;
        private string _SortExpression = "";
        private int _iNumPage = 0;
        private int _iNumRecords = 0;
        private int _intTotalRecords = 0;
        private int _intTotalPages = 0;
        private int _intEmpresa;
        private int _intSucursal;
        private int _intFolioInicial;
        private int _intFolioFinal;
        private int _intParametroInicial;
        private int _intParametroFinal;
        private int _intProveedorInicial;
        private int _intProveedorFinal;
        private string _strFechaInicial;
        private string _strFechaFinal;
        private string _strObraInicial;
        private string _strObraFinal;
        private string _strInsumoInicial;
        private string _strInsumoFinal;  
        private string _strUsuario;
        private string _strMaquina;
        private int _intMenu;
        private string _strKeys;
        private int _intEjercicioInicial;
        private int _intEjercicioFinal;
        private int _intMesInicial;
        private int _intMesFinal;
        private decimal _dblCargos;
        private decimal _dblAbonos;
        private decimal _dblTotal;

        public int SortDirection
        {
            get
            {
                return this._SortDirection;
            }
            set
            {
                this._SortDirection = value;
            }
        }

        public string SortExpression
        {
            get
            {
                return this._SortExpression;
            }
            set
            {
                this._SortExpression = value;
            }
        }

        public int iNumPage
        {
            get { return _iNumPage; }
            set { _iNumPage = value; }
        }

        public int iNumRecords
        {
            get { return _iNumRecords; }
            set { _iNumRecords = value; }
        }

        public int IntEmpresa
        {
            get { return _intEmpresa; }
            set { _intEmpresa = value; }
        }

        public int IntSucursal
        {
            get { return _intSucursal; }
            set { _intSucursal = value; }
        }

        public string StrUsuario
        {
            get { return _strUsuario; }
            set { _strUsuario = value; }
        }

        public string StrMaquina
        {
            get { return _strMaquina; }
            set { _strMaquina = value; }
        }

        public int IntMenu
        {
            get { return _intMenu; }
            set { _intMenu = value; }
        }

        public int IntFolioInicial
        {
            get { return _intFolioInicial; }
            set { _intFolioInicial = value; }
        }

        public int intFolioFinal
        {
            get { return _intFolioFinal; }
            set { _intFolioFinal = value; }
        }

        public string StrFechaInicial
        {
            get { return _strFechaInicial; }
            set { _strFechaInicial = value; }
        }

        public string StrFechaFinal
        {
            get { return _strFechaFinal; }
            set { _strFechaFinal = value; }
        }

        public string strKeys
        {
            get { return _strKeys; }
            set { _strKeys = value; }
        }

        public int IntTotalRecords
        {
            get { return _intTotalRecords; }
            set { _intTotalRecords = value; }
        }

        public int IntTotalPages
        {
            get { return _intTotalPages; }
            set { _intTotalPages = value; }
        }

        public string StrObraInicial
        {
            get { return _strObraInicial; }
            set { _strObraInicial = value; }
        }

        public string StrObraFinal
        {
            get { return _strObraFinal; }
            set { _strObraFinal = value; }
        }

        public string StrInsumoInicial
        {
            get { return _strInsumoInicial; }
            set { _strInsumoInicial = value; }
        }

        public string StrInsumoFinal
        {
            get { return _strInsumoFinal; }
            set { _strInsumoFinal = value; }
        }

        public int IntProveedorInicial
        {
            get { return _intProveedorInicial; }
            set { _intProveedorInicial = value; }
        }

        public int IntProveedorFinal
        {
            get { return _intProveedorFinal; }
            set { _intProveedorFinal = value; }
        }

        public int IntParametroInicial
        {
            get { return _intParametroInicial; }
            set { _intParametroInicial = value; }
        }

        public int IntParametroFinal
        {
            get { return _intParametroFinal; }
            set { _intParametroFinal = value; }
        }

        public int IntEjercicioInicial
        {
            get { return _intEjercicioInicial; }
            set { _intEjercicioInicial = value; }
        }

        public int IntEjercicioFinal
        {
            get { return _intEjercicioFinal; }
            set { _intEjercicioFinal = value; }
        }

        public int IntMesInicial
        {
            get { return _intMesInicial; }
            set { _intMesInicial = value; }
        }

        public int IntMesFinal
        {
            get { return _intMesFinal; }
            set { _intMesFinal = value; }
        }

        public decimal DblCargos
        {
            get { return _dblCargos; }
            set { _dblCargos = value; }
        }

        public decimal DblAbonos
        {
            get { return _dblAbonos; }
            set { _dblAbonos = value; }
        }

        public decimal DblTotal
        {
            get { return _dblTotal; }
            set { _dblTotal = value; }
        }

    }
}
