/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_Poliza : EntityBaseClass
	{
        private string _Empresa;
        private int _intEjercicio;
        private int _intMes;
        private int _intModulo;
        private int _intAfectada;        
        private string _Fecha;
        private string _TipoPoliza;
        private string _strPoliza;
			
        #region Empresa
        public string Empresa
		    {
                get
                {
                    return _Empresa;
                }
                set
                {
                    _Empresa = value;
                }
			}
			#endregion 

            #region Fecha
            public string Fecha
		    {
                get
                {
                    return _Fecha;
                }
                set
                {
                    _Fecha = value;
                }
			}
			#endregion 

            #region TipoPoliza
            public string TipoPoliza
		    {
                get
                {
                    return _TipoPoliza;
                }
                set
                {
                    _TipoPoliza = value;
                }
			}
			#endregion 

            #region StrPoliza
            public string StrPoliza
        {
            get
            {
                return _strPoliza;
            }
            set
            {
                _strPoliza = value;
            }
        }
        #endregion     

        #region IntEjercicio
        public int IntEjercicio
        {
            get
            {
                return _intEjercicio;
            }
            set
            {
                _intEjercicio = value;
            }
        }
        #endregion 

        #region IntMes
        public int IntMes
        {
            get
            {
                return _intMes;
            }
            set
            {
                _intMes = value;
            }
        }
        #endregion 

        #region IntModulo
        public int IntModulo
        {
            get
            {
                return _intModulo;
            }
            set
            {
                _intModulo = value;
            }
        }
        #endregion

        #region IntAfectada
        public int IntAfectada
        {
            get
            {
                return _intAfectada;
            }
            set
            {
                _intAfectada = value;
            }
        }
        #endregion 

	}
}
