/*
'===============================================================================
'  Company: IASD
'  Autor: Ingrid Soto Dimas
'  Date: 2013-09-04
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

namespace Contabilidad.Entity
{
    public class Entity_PolizasEnc : EntityBaseClass
	{
        public string  _strClasifEnc;
        public int _intEjercicio;
        public int _intMes;
        public string  _strPoliza;
        public string  _strTipoPoliza;
        public int _intFolioPoliza;
        public DateTime  _datFecha;
        public int _intEstatus;
        public string _strDescripcion;
        public decimal  _dblCargos;
        public decimal _dblAbonos;
        public int _intIndAfectada;
        public int _intIndInterempresa;
        public int _intIndRec;
        public int _intIndGenRec;
        public int _intEjercicioOr;
        public int _intMesOr;
        public string _strPolizaOr;
        public int _intConFlujo;
        public string _strAuditAlta;
        public string  _strAuditMod;
        public decimal _dblTransmision;
        public int _intCuentaBancaria;
        public int _intCheque;
        public int _intPartida;
        public int _intCenCos;
        public int _intTransferencia;
        public string _strFolio;

        public string strClasifEnc
        {
            get
            {
                return _strClasifEnc;
            }
            set
            {
                _strClasifEnc = value;
            }
        }

        public int intEjercicio
        {
            get
            {
                return _intEjercicio;
            }
            set
            {
                _intEjercicio = value;
            }
        }

        public int intMes
        {
            get
            {
                return _intMes;
            }
            set
            {
                _intMes = value;
            }
        }

        public string  strPoliza
        {
            get
            {
                return _strPoliza;
            }
            set
            {
                _strPoliza = value;
            }
        }

        public string strTipoPoliza
        {
            get
            {
                return _strTipoPoliza;
            }
            set
            {
                _strTipoPoliza = value;
            }
        }

        public int intFolioPoliza
        {
            get
            {
                return _intFolioPoliza;
            }
            set
            {
                _intFolioPoliza = value;
            }
        }

        public DateTime datFecha
        {
            get
            {
                return _datFecha;
            }
            set
            {
                _datFecha = value;
            }
        }

        public int intEstatus
        {
            get
            {
                return _intEstatus;
            }
            set
            {
                _intEstatus = value;
            }
        }

        public string strDescripcion
        {
            get
            {
                return _strDescripcion;
            }
            set
            {
                _strDescripcion = value;
            }
        }

        public decimal dblCargos
        {
            get
            {
                return _dblCargos;
            }
            set
            {
                _dblCargos = value;
            }
        }

        public decimal dblAbonos
        {
            get
            {
                return _dblAbonos;
            }
            set
            {
                _dblAbonos = value;
            }
        }

        public int intIndAfectada
        {
            get
            {
                return _intIndAfectada;
            }
            set
            {
                _intIndAfectada = value;
            }
        }

        public int intIndInterempresa
        {
            get
            {
                return _intIndInterempresa;
            }
            set
            {
                _intIndInterempresa = value;
            }
        }

        public int intIndRec
        {
            get
            {
                return _intIndRec;
            }
            set
            {
                _intIndRec = value;
            }
        }

        public int intIndGenRec
        {
            get
            {
                return _intIndGenRec;
            }
            set
            {
                _intIndGenRec = value;
            }
        }

        public int intEjercicioOr
        {
            get
            {
                return _intEjercicioOr;
            }
            set
            {
                _intEjercicioOr = value;
            }
        }

        public int intMesOr
        {
            get
            {
                return _intMesOr;
            }
            set
            {
                _intMesOr = value;
            }
        }

        public string strPolizaOr
        {
            get
            {
                return _strPolizaOr;
            }
            set
            {
                _strPolizaOr = value;
            }
        }

        public int intConFlujo
        {
            get
            {
                return _intConFlujo;
            }
            set
            {
                _intConFlujo = value;
            }
        }

        public string strAuditAlta
        {
            get
            {
                return _strAuditAlta;
            }
            set
            {
                _strAuditAlta = value;
            }
        }

        public string strAuditMod
        {
            get
            {
                return _strAuditMod;
            }
            set
            {
                _strAuditMod = value;
            }
        }

        public decimal dblTransmision
        {
            get
            {
                return _dblTransmision;
            }
            set
            {
                _dblTransmision = value;
            }
        }

        public int intCuentaBancaria
        {
            get
            {
                return _intCuentaBancaria;
            }
            set
            {
                _intCuentaBancaria = value;
            }
        }

        public int intCheque
        {
            get
            {
                return _intCheque;
            }
            set
            {
                _intCheque = value;
            }
        }

        public int intPartida
        {
            get
            {
                return _intPartida;
            }
            set
            {
                _intPartida = value;
            }
        }

        public int intCenCos
        {
            get
            {
                return _intCenCos;
            }
            set
            {
                _intCenCos = value;
            }
        }

        public int intTransferencia
        {
            get
            {
                return _intTransferencia;
            }
            set
            {
                _intTransferencia = value;
            }
        }

        public string StrFolio
        {
            get
            {
                return _strFolio;
            }
            set
            {
                _strFolio = value;
            }
        }
    }
}
