/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using System.Collections.Specialized;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class Factura
    {

        #region Variables

        int _ReturnValue;
        public int ReturnValue
        {
            get { return _ReturnValue; }
            set { _ReturnValue = value; }
        }
        #endregion Variables

        #region GetList
        public DataTable GetList(Entity_Factura obj)
        {
            return DACFactura.GetList(obj);                   
        }
        #endregion       

        #region Fill
        public Entity_Factura Fill(Entity_Factura obj)
        {
            return DACFactura.Fill(obj); 
        }
        #endregion

        #region GetByProveedor
        public string GetByProveedor(Entity_Factura obj)
        {
            return DACFactura.GetByProveedor(obj); 
        }
        #endregion

        #region ValidaOC
        public string ValidaOC(Entity_Factura obj)
        {
            return DACFactura.ValidaOC(obj); 
        }
        #endregion
       
        #region Save
        public string Save(Entity_Factura obj)
        {
            return DACFactura.Save(obj); 
        }
        #endregion

        #region SaveDig
        public string SaveDig(Entity_Factura obj)
        {
            return DACFactura.SaveDig(obj);
        }
        #endregion

        #region Delete
        public bool Delete(Entity_Factura obj)
        {
            return DACFactura.Delete(obj); 
        }

        #endregion Delete

        #region DeleteContraRecibo
        public bool DeleteContraRecibo(Entity_Factura obj)
        {
            return DACFactura.DeleteContraRecibo(obj); 
        }

        #endregion Delete

        #region GetListEmail
        public DataTable GetListEmail(Entity_Factura obj)
        {
            return DACFactura.GetListEmail(obj);
        }
        #endregion   

        #region EmailSave
        public bool EmailSave(Entity_Factura obj)
        {
            return DACFactura.EmailSave(obj);
        }
        #endregion   

        #region ExportContraRecibo
        public string ExportContraRecibo(Entity_Factura obj)
        {
            string value = "VetecMarfilAdmin..usp_tbFacXP_ListEmail ";
            value = value + obj.IntEmpresa.ToString() + ",";
            value = value + obj.IntProveedor.ToString() + ",'";
            value = value + obj.StrFechaInicial + "','";
            value = value + obj.StrFechaFinal + "',";
            value = value + obj.IntEnviado.ToString() + ",";
            value = value + obj.SortDirection + ",";
            value = value + obj.SortExpression + ",";
            value = value + obj.iNumPage.ToString() + ",";
            value = value + obj.iNumRecords.ToString(); ;
            
            return value;
        }
        #endregion

        #region GetListMov
        public DataTable GetListMov(Entity_Factura obj)
        {
            return DACFactura.GetListMov(obj);
        }
        #endregion  

        #region ExportTM
        public string ExportTM(Entity_Factura obj)
        {
            string value = "usp_tbFacXP_RelacionTM ";
            value = value + obj.IntEmpresa.ToString() + ",'";
            value = value + obj.StrFechaInicial + "','";
            value = value + obj.StrFechaFinal + "','";
            value = value + obj.StrObraInicial + "','";
            value = value + obj.StrObraFinal + "',";                      
            value = value + obj.IntProveedorInicial + ",";
            value = value + obj.IntProveedorFinal + ",";
            value = value + obj.IntParametroInicial + ",";
            value = value + obj.IntParametroFinal + ",";
            value = value + obj.IntFolioInicial + ",";
            value = value + obj.intFolioFinal;

            return value;
        }
        #endregion
    }
}
