/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class FacturaDet
    {

        #region GetList
        public DataTable GetList(Entity_Factura obj)
        {
            return DACFacturaDet.GetList(obj);
        }
        #endregion

        #region Fill
        public Entity_FacturaDet Fill(Entity_FacturaDet obj)
        {
            return DACFacturaDet.Fill(obj);
        }
        #endregion      

        #region Save
        public string Save(Entity_FacturaDet obj)
        {
            return DACFacturaDet.Save(obj);
        }
        #endregion

        #region Delete
        public bool Delete(Entity_FacturaDet obj)
        {
            return DACFacturaDet.Delete(obj);
        }

        #endregion Delete

        #region GetListMov
        public DataTable GetListMov(Entity_FacturaDet obj)
        {
            return DACFacturaDet.GetListMov(obj);
        }
        #endregion
    }
}
