/*
'===============================================================================
'  Company: RMM
'  Autor: Rubén Mora Martínez
'  Date: 2011-07-29
'  **** Generated by MyGeneration Version # (1.3.0.3) ****
'===============================================================================
*/

using System;
using System.Data;
using System.Collections;
using Contabilidad.DataAccess;
using Contabilidad.Entity;

namespace Contabilidad.Bussines
{
    public class List
    {
        #region Ejercicio
        public DataTable Ejercicio(int intEmpresa, int intSucursal)
        {
            return DACList.Ejercicio(intEmpresa, intSucursal);
        }
        #endregion

        #region Colonia
        public DataTable Colonia(int intEmpresa, int intSucursal)
        {
            return DACList.Colonia(intEmpresa, intSucursal);
        }
        #endregion

        #region TipoCredito
        public DataTable TipoCredito(int intEmpresa, int intSucursal)
        {
            return DACList.TipoCredito(intEmpresa, intSucursal);
        }
        #endregion

        #region TiposGruposContables
        public DataTable TiposGruposContables(int intEmpresa, int intSucursal)
        {
            return DACList.TiposGruposContables(intEmpresa, intSucursal);
        }
        #endregion

        #region Moneda
        public DataTable Moneda(int intEmpresa, int intSucursal)
        {
            return DACList.Moneda(intEmpresa, intSucursal);
        }
        #endregion

        #region RubrosTipo
        public DataTable RubrosTipo(int intEmpresa, int intSucursal)
        {
            return DACList.RubrosTipo(intEmpresa, intSucursal);
        }
        #endregion

        #region TM
        public DataTable TM(int intEmpresa, int intSucursal)
        {
            return DACList.TM(intEmpresa, intSucursal);
        }
        #endregion
       
    }
}
